<?php
$interactions=$this->$interaction;

?>
<table class="table" width="100%">
    <tr>
        <th>
            Номер предложения
        </th>
        <th>
            Для чего предложили
        </th>
        <th>
            Что предложили
        </th>
        <th>
            Статус
         </th>

    </tr>
<?php foreach($interactions as $interaction) { ?>
    <tr>
        <td>
        <?php if($au['str']=='up') echo 'Ресурс';
              else echo 'Заявка';?>
        </td>
        <td>
        </td>
        <td>
        <?php if($au['str']=='up') echo 'Минимальная: '. $au['money'].' '. $au['currency'] ;
                      else echo 'Максимальная: '. $au['money'].' '. $au['currency'] ; ?>
        </td>
        <td>
                <a href="<?php echo $this->url('interaction',
                    array('action'=>'addBid', 'id' => $au['uuid']));?>">Сделать ставку</a>
        </td>
        <td>
                <a href="<?php echo $this->url('interaction',
                    array('action'=>'list', 'id' => $au['uuid']));?>">Подробнее</a>
        </td>
    </tr>
<?php } ?>
</table>
