<?php
$auc=$this->auc;

?>
<table class="table" width="100%">
    <tr>
        <th>
            Тип аукциона
        </th>
        <th>
            Текущая ставка
        </th>
        <th>
            Ставка
        </th>
        <th>
            Сделать ставка
         </th>
        <th>
            Подробнее
        </th>
    </tr>
<?php foreach($auc as $au) { ?>
    <tr>
        <td>
        <?php if($au['str']=='up') echo 'Ресурс';
              else echo 'Заявка';?>
        </td>
        <td>
        </td>
        <td>
        <?php if($au['str']=='up') echo 'Минимальная: '. $au['money'].' '. $au['currency'] ;
                      else echo 'Максимальная: '. $au['money'].' '. $au['currency'] ; ?>
        </td>
        <td>
                <a href="<?php echo $this->url('interaction',
                    array('action'=>'addBid', 'id' => $au['uuid']));?>">Сделать ставку</a>
        </td>
        <td>
                <a href="<?php echo $this->url('interaction',
                    array('action'=>'list', 'id' => $au['uuid']));?>">Подробнее</a>
        </td>
    </tr>
<?php } ?>
</table>
