<?php

$field = $this->field;
$list = $this->list;


?>



<h1> <?php
    echo $list['fieldRusName'];
    ?></h1>

<a href="<?php echo $this->url(
    'addList',
    array('action' => 'add', 'id' => $list['uuid'])
);?>">Добавить поле в список</a>

<table class="table">
    <tr>
        <th>
            Имя поля
        </th>
        <th>
            Просмотр полей
        </th>
        <th>
            Добавить поля
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php
    foreach($field as $fi) {
        ?>

        <tr>
            <td>
                <?php
                echo $fi['value'];
                ?>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'addList',
                    array('action' => 'my-fields', 'id' => $fi['uuid'],'parent'=>'parent')
                );?>">Посмотреть поля</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'addList',
                    array('action' => 'add', 'id' => $fi['uuid'],'parent'=>'parent')
                );?>">Добавить</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'addList',
                    array('action' => 'edit', 'id' => $fi['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'addList',
                    array('action' => 'delete', 'id' => $fi['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php
    }
    ?>
</table>
