<?php
// module/Album/view/album/album/add.phtml:
$form=$this->form;
$form->setAttribute('action', $this->url('organization', array('action' => 'createOrganization')))
    ->prepare();

echo $this->form()->openTag($form);

$org = $form->get('organization');
echo $this->formRow($org->get('name'));
echo $this->formRow($org->get('type'));
echo $this->formRow($org->get('description'));
echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?> <a href="<?php echo $this->url('organization', array('action'=>'index'));?>">Вернуться в организации</a>
