<?php $form=$this->form;
$form->setAttribute('action', $this->url('account', array('action' => 'choiceOrgAndCompany')))
    ->prepare();

echo $this->form()->openTag($form);
$currentOrg=$form->get('currentOrg')->setAttributes(array('onclick' =>"$('select[name=currentCom]').html('<option>Сначала выберите организацию и сохраните результат</option>');"));
?>
<div class="companyAdd">
    <?php


    echo $this->formRow($currentOrg);
    echo '<p>Сначала выберите организацию, и сохранить результат, после этого будут доступны компании</p>';
    echo $this->formRow($form->get('currentCom'));

    echo $this->formElement($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
<?php

?> <a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
