<?php
// module/Album/view/album/album/add.phtml:
$form=$this->form;
$form->setAttribute('action', $this->url('organization', array('action' => 'createOrganization', 'id'=>$this->uuid)))
    ->prepare();

echo $this->form()->openTag($form);
//die(var_dump($org));
$org = $form->get('organization');
echo $this->formRow($org->get('name')->setValue($this->org['name']));
echo $this->formRow($org->get('type')->setValue($this->org['type']));
echo $this->formRow($org->get('description')->setValue($this->org['description']));
echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
