<?php
$title = 'Аккаунт';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
 <?php if(empty($this->org)) { ?>   <a href="<?php echo $this->url('account', array('action'=>'add'));?>">Добавить организацию</a>
 <?php } ?>
</p>

    <?php if(!empty($this->org)) {
    $oc=$this->org[0];
     $o=$oc['org']?>
        <table class="table">
            <tr>
                <th>Название организации</th>

            </tr>
        <tr>
            <td><a href="<?php echo $this->url('account',
                    array('action'=>'list', 'id' => $o['uuid']));?>"><?php echo $o['name']; ?></a></td>

            </tr>

</table>
<table class="table">
<tr>
                <th>Добавить юр. лицо</th>

<th>Добавить админа к аккаунту</th>
<th>Список админов</th>
                </tr>
                <tr>
                <td><a href="<?php echo $this->url('company',
                                    array('action'=>'add', 'org_id' => $o['uuid']));?>">Добавить</a></td>
                         <td><a href="<?php echo $this->url('company_user',
                                                array('action'=>'add', 'org_id' => $o['uuid'] , 'param' => 'admin'));?>">Добавить</a></td>
  <td><a href="<?php echo $this->url('company_user', array('action'=>'list','org_id'=>$o['uuid'], 'param' => 'admin'));?>">Посмотреть админов</a></td>
                        </tr>

</table>
       <table class="table">
       <tr>
                       <th>Список юр. лиц</th>
                       <th>Список всех юзеров аккаунта</th>

                       </tr>
                       <tr>
                       <td><a href="<?php echo $this->url('company', array('action'=>'index','org_id'=>$o['uuid']));?>">Посмотреть юр. лица</a></td>
                                   <td><a href="<?php echo $this->url('company_user', array('action'=>'list','org_id'=>$o['uuid'], 'param' => 'user'));?>">Посмотреть юзеров</a></td>

                               </tr>

       </table>


        <table style="background:#ccc;" class="table">
            <tr>
                <th>Название юр. лица</th>
                  <th>Юзеры юр. лица</th>
                   <th>Добавить юзера в компаню</th>
            </tr>
            <?php foreach($oc['com'] as $c) {  ?>
                <tr>
                    <td><a href="<?php echo $this->url('company',
                            array('action'=>'list', 'org_id'=>$o['uuid'],'id' => $c['uuid']));?>"><?php echo $c['name']; ?></a></td>
       <td>
                <a href="<?php echo $this->url('company_user', array('action'=>'list','org_id'=>$c['uuid'], 'param' => 'current'));?>">Посмотреть юзеров</a></td>
                                              <td><a href="<?php echo $this->url('company_user',
                                                                            array('action'=>'add', 'org_id' => $c['uuid']));?>">Добавить</a></td>


                <td>
                                <a href="<?php echo $this->url('company',
                                    array('action'=>'edit', 'id' => $c['uuid'], 'org_id' => $o['uuid']));?>">Редактировать</a>
                                <a href="<?php echo $this->url('company',
                                    array('action'=>'delete', 'id' => $c['uuid'],'org_id' => $o['uuid']));?>">Удалить</a>
                </td>
                </tr>
            <?php  ?>

        </table>
        </br></br>
    <?php } } ?>