<?php
$title = 'Организации';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
 <?php if(empty($this->org)) { ?>   <a href="<?php echo $this->url('organization', array('action'=>'add'));?>">Добавить организацию</a>
 <?php } ?>
</p>

    <?php if(!empty($this->org)) { foreach($this->org as $oc) { $o=$oc['org']?>
        <table class="table">
            <tr>
                <th>Название организации</th>
                <th>Тип организации</th>
                <th>Описание организации</th>
                <th>Добавить компанию</th>
                <th>Добавить юзера в организацию</th>
                <th>&nbsp;</th>
            </tr>
        <tr>
            <td><a href="<?php echo $this->url('organization',
                    array('action'=>'list', 'id' => $o['uuid']));?>"><?php echo $o['name']; ?></a></td>
            <td><?php echo $o['type']; ?></td>
            <td><?php echo $o['description']; ?></td>
            <td><a href="<?php echo $this->url('company',
                    array('action'=>'add', 'org_id' => $o['uuid']));?>">Добавить</a></td>
            <td><a href="<?php echo $this->url('company_user',
                    array('action'=>'add', 'org_id' => $o['uuid']));?>">Добавить</a></td>
            <td>
                <a href="<?php echo $this->url('organization',
                    array('action'=>'edit', 'id' => $o['uuid']));?>">Редактировать</a>
                <a href="<?php echo $this->url('organization',
                    array('action'=>'delete', 'id' => $o['uuid']));?>">Удалить</a>
            </td>
        </tr>

</table>
        <p>
            <a href="<?php echo $this->url('company', array('action'=>'index','org_id'=>$o['uuid']));?>">Список компаний</a>
        </p>
        <table style="background:#ccc;" class="table">
            <tr>
                <th>Название компании</th>
            </tr>
            <?php foreach($oc['com'] as $c) { ?>
                <tr>
                    <td><a href="<?php echo $this->url('company',
                            array('action'=>'list', 'org_id'=>$o['uuid'],'id' => $c['uuid']));?>"><?php echo $c['name']; ?></a></td>
                <td>
                                <a href="<?php echo $this->url('company',
                                    array('action'=>'edit', 'id' => $c['uuid'], 'org_id' => $o['uuid']));?>">Редактировать</a>
                                <a href="<?php echo $this->url('company',
                                    array('action'=>'delete', 'id' => $c['uuid'],'org_id' => $o['uuid']));?>">Удалить</a>
                </td>
                </tr>
            <?php } ?>

        </table>
        </br></br>
    <?php } } ?>

<h1>Заявки вашей организации</h1>
<?php
if(!empty($this->org)) {
$tickets=$this->tick;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>
<a href="<?php echo $this->url('ticket',
    array('action'=>'add'));?>">Добавить заявку</a>
<a href="<?php echo $this->url('ticket',
    array('action'=>'my'));?>">Мои заявки</a>

<table class="table">
    <tr>
    <th>
        Типы перевозок
    </th>
    <th>
        Промежуток когда свободен ресурс
    </th>
    <th>
        Стоимость
    </th>
    <th>
        Подробнее
     </th>
              <th>
                  Редактировать
               </th>
         <th>
             Добавить аукцион
          </th>
    </tr>
    <?php foreach ($tickets as $ticket) { $ticket=$ticket['tick'];?>
<tr>
    <td>
        <?php foreach ($types_r as $key => $value) {
            echo $key.' '.$ticket[$value].' ';
        }
        ?>
    </td>
    <td>
        <?php echo $ticket['dateStart'].' / '.$ticket['dateEnd']; ?>
    </td>
    <td>
        <?php echo $ticket['money'].' '.$ticket['currency']; ?>
    </td>
    <td>
        <a href="<?php echo $this->url('ticket',
            array('action'=>'list', 'id' => $ticket['uuid']));?>">Подробнее</a>
    </td>
                <td>
                    <a href="<?php echo $this->url('ticket',
                        array('action'=>'edit', 'id' => $resource['uuid']));?>">Редактировать</a>
                </td>
        <td>
            <a href="<?php echo $this->url('auction',
                array('action'=>'add', 'id' => $ticket['uuid']));?>">Добавить аукцион</a>
        </td>
</tr>
    <?php } ?>

</table>
<h1>Ресурсы вашей организации</h1>
<?php
$resources=$this->res;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>


<a href="<?php echo $this->url('resource',
    array('action'=>'add'));?>">Добавить ресурс</a>

<a href="<?php echo $this->url('resource',
    array('action'=>'my'));?>">Мои ресурсы</a>

<table class="table">
    <tr>
    <th>
        Типы перевозок
    </th>
    <th>
        Промежуток когда свободен ресурс
    </th>
    <th>
        Стоимость
    </th>
    <th>
        Подробнее
     </th>
         <th>
             Редактировать
          </th>
         <th>
             Добавить аукцион
          </th>
    </tr>
    <?php foreach ($resources as $resource) { $resource=$resource['res'];?>
<tr>
    <td>
        <?php foreach ($types_r as $key => $value) {
            echo $key.' '.$resource[$value].' ';
        }
        ?>
    </td>
    <td>
        <?php echo $resource['dateStart'].' / '.$resource['dateEnd']; ?>
    </td>
    <td>
        <?php echo $resource['money'].' '.$resource['currency']; ?>
    </td>
    <td>
        <a href="<?php echo $this->url('resource',
            array('action'=>'list', 'id' => $resource['uuid']));?>">Подробнее</a>
    </td>
                <td>
                    <a href="<?php echo $this->url('resource',
                        array('action'=>'edit', 'id' => $resource['uuid']));?>">Редактировать</a>
                </td>
        <td>
            <a href="<?php echo $this->url('auction',
                array('action'=>'add', 'id' => $resource['uuid']));?>">Добавить аукцион</a>
        </td>
</tr>
    <?php } ?>

</table>
 <?php } ?>