<?php
$title = 'Организации';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('organization', array('action'=>'add'));?>">Добавить организацию</a>
</p>

<table class="table">
    <tr>
        <th>Название организации</th>
        <th>Тип организации</th>
        <th>Описание организации</th>
        <th>Добавить компанию</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->org as $o) { ?>
        <tr>
            <td><a href="<?php echo $this->url('organization',
                    array('action'=>'list', 'id' => $o['uuid']));?>"><?php echo $o['name']; ?></a></td>
            <td><?php echo $o['type']; ?></td>
            <td><?php echo $o['description']; ?></td>
            <td><a href="<?php echo $this->url('company',
                    array('action'=>'add', 'org_id' => $o['uuid']));?>">Добавить</a></td>
            <td>
                <a href="<?php echo $this->url('organization',
                    array('action'=>'edit', 'id' => $o['uuid']));?>">Edit</a>
                <a href="<?php echo $this->url('organization',
                    array('action'=>'delete', 'id' => $o['uuid']));?>">Delete</a>


            </td>
        </tr>
    <?php } ?>
</table>

