<?php
$o = $this->org;
if (!$o) {
    echo '<p>Такой организации не существует</p>';
} else {

    $title = 'Организация: ' . $o['name'];
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($o['name']); ?></h1>
    <p>Тип организации: <?php echo $o['type']; ?></p>
    <p>Описание организации: <?php echo $o['type']; ?></p>
    <p>Владелец организации: <?php echo $o['orgOwner']; ?></p>
    </br>
    <a href="<?php echo $this->url(
        'account',
        array('action' => 'edit', 'id' => $o['uuid'])
    );?>">Редактировать</a>
    <a href="<?php echo $this->url(
        'account',
        array('action' => 'delete', 'id' => $o['uuid'])
    );?>">Удалить</a>
    <a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в организации</a>

<?php } ?>