<?php
$param=$this->param;
$form = $this->form;
$formRoles=$this->formRoles;
$form->setAttribute('action', $this->url('company_user', array('action' => 'addUser', 'org_id' => $this->org_id, 'param' =>$param)))
    ->prepare();

echo $this->form()->openTag($form);

$acc = $form->get('company_user');
echo $this->formRow($acc->get('email'));
echo $this->formHidden($form->get('csrf'));
if(!empty($formRoles)) {
    echo $this->formRow($formRoles->get('roles'));
}
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
