<?php
$form = $this->form;
$formData= $this->formData;
$form->setAttribute('action', $this->url('vehicle', array('action' => 'addVehicle')))
    ->prepare();
$name = $form->get('name');

$serialNumber= $form->get('serialNumber');
$vin= $form->get('vin');
$mark= $form->get('mark');
$model= $form->get('model');

$type= $form->get('type');

$status= $form->get('status');
$dateMade= $form->get('dateMade');
$owner= $form->get('owner');

$serialNumberDoc= $form->get('serialNumberDoc');
$carNumber= $form->get('carNumber');
$ecologicalClass= $form->get('ecologicalClass');
$allowedMaxMass= $form->get('allowedMaxMass');
$axles= $form->get('axles');
$capacity= $form->get('capacity');
$ownerName= $form->get('ownerName');
$whoGave= $form->get('whoGave');

echo $this->form()->openTag($form);




?>
<table class="table spec_table vehicle">
    <tr >
        <th style="width:50%; text-align: center;">
            ПТС
        </th>
        <th style="width:50%; text-align: center;">
            Свидетельстов о регистрации
        </th>
    </tr>
    <tr style="border-right: 1px dashed #dddddd;">
        <td style="width:50%;">
            <?php
            echo $this->formRow($serialNumber);
            echo $this->formRow($vin);
            echo $this->formRow($mark);
            echo $this->formRow($model);
            echo $this->formRow($type);
            echo $this->formRow($dateMade);
            echo $this->formRow($owner);
            ?>
        </td>
        <td style="width:50%;">
            <?php
            echo $this->formRow($serialNumberDoc);
            echo $this->formRow($carNumber);
            echo $this->formRow($ecologicalClass);
            echo $this->formRow($allowedMaxMass);
            echo $this->formRow($axles);
            echo $this->formRow($capacity);
            echo $this->formRow($ownerName);
            echo $this->formRow($whoGave);
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php  echo $this->formRow($status); ?>
        </td>
    </tr>
    </table>

    <div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>