<?php
$form = $this->form;
$form->setAttribute('action', $this->url('vehicle', array('action' => 'addVehicle', 'id' => $this->id)))
    ->prepare();
$name = $form->get('name');

$serialNumber= $form->get('serialNumber')->setValue($this->res['serialNumber']);
$vin= $form->get('vin')->setValue($this->res['vin']);
$mark= $form->get('mark')->setValue($this->res['mark']);
$model= $form->get('model')->setValue($this->res['model']);
$type= $form->get('type')->setValue($this->res['type']);
$dateMade= $form->get('dateMade')->setValue($this->res['dateMade']);
$owner= $form->get('owner')->setValue($this->res['owner']);

$serialNumberDoc= $form->get('serialNumberDoc')->setValue($this->res['serialNumberDoc']);
$carNumber= $form->get('carNumber')->setValue($this->res['carNumber']);
$ecologicalClass= $form->get('ecologicalClass')->setValue($this->res['ecologicalClass']);
$allowedMaxMass= $form->get('allowedMaxMass')->setValue($this->res['allowedMaxMass']);
$axles= $form->get('axles')->setValue($this->res['axles']);
$capacity= $form->get('capacity')->setValue($this->res['capacity']);
$ownerName= $form->get('ownerName')->setValue($this->res['ownerName']);
$whoGave= $form->get('whoGave')->setValue($this->res['whoGave']);

echo $this->form()->openTag($form);


echo $this->formRow($tent);

?>
    <table class="table spec_table">
        <tr >
            <th style="width:50%; text-align: center;">
                ПТС
            </th>
            <th style="width:50%; text-align: center;">
                Свидетельстов о регистрации
            </th>
        </tr>
        <tr style="border-right: 1px dashed #dddddd;">
            <td style="width:50%;">
                <?php
                echo $this->formRow($serialNumber);
                echo $this->formRow($vin);
                echo $this->formRow($mark);
                echo $this->formRow($model);
                echo $this->formRow($type);
                echo $this->formRow($dateMade);
                echo $this->formRow($owner);
                ?>
            </td>
            <td style="width:50%;">
                <?php
                echo $this->formRow($serialNumberDoc);
                echo $this->formRow($carNumber);
                echo $this->formRow($ecologicalClass);
                echo $this->formRow($allowedMaxMass);
                echo $this->formRow($axles);
                echo $this->formRow($capacity);
                echo $this->formRow($ownerName);
                echo $this->formRow($whoGave);
                ?>
            </td>
        </tr>
    </table>
    <div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>