<?php
$vehicles = $this->res;



?>
<h1>Все ТС</h1>

<table class="table">
    <tr>
        <th>
            Номер транспортного средства
        </th>
        <th>
            Статус
        </th>
        <th>
            Марка / Модель
        </th>


    </tr>
    <?php foreach ($vehicles as $vehicle) {
        $acc = $vehicle['owner'];
        $vehicle = $vehicle['res']; ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'add', 'id' => $vehicle['uuid'], 'type' => 'list')
                ); ?>">
                    <?php echo $vehicle['carNumber']; ?>
                </a>

            </td>
            <td>
                <?php echo $vehicle['status']; ?>
            </td>
            <td>
                <?php echo $vehicle['mark'] . ' / ' . $vehicle['model']; ?>
            </td>

            <!--      <td>
                    <a href="<?php echo $this->url('account',
                                array('action'=>'list', 'id' => $acc['uuid']));?>"><?php echo $acc['name']; ?></a>
                    </td>

            <td>
                <a href="<?php echo $this->url( 'vehicle',array('action' => 'add', 'id' => $vehicle['uuid'], 'type' => 'edit'));?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'delete', 'id' => $vehicle['uuid'])
                );?>">Удалить</a>
            </td> -->
        </tr>
    <?php } ?>

</table>