<?php
$vehicles = $this->res;



?>
<h1>Все ТС</h1>

<table class="table">
    <tr>
        <th>
           Номер транспортного средства
        </th>
                <th>
                    Статус
                </th>
        <th>
            Марка / Модель
        </th>

        <th>
            Организация
        </th>
        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($vehicles as $vehicle) { $org=$vehicle['org'];$vehicle=$vehicle['res'];?>
        <tr>
            <td>
                 <?php echo $vehicle['carNumber']; ?>
            </td>
                        <td>
                            <?php echo $vehicle['status']; ?>
                        </td>
            <td>
                <?php echo $vehicle['mark'] . ' / ' . $vehicle['model']; ?>
            </td>

                    <td>
                    <a href="<?php echo $this->url('organization',
                                array('action'=>'list', 'id' => $org['uuid']));?>"><?php echo $org['name']; ?></a>
                    </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'list', 'id' => $vehicle['uuid'])
                );?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'edit', 'id' => $vehicle['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'delete', 'id' => $vehicle['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>