<?php
$vehicles = $this->res;


?>
<a href="<?php echo $this->url(
    'vehicle',
    array('action' => 'add')
);?>">Добавить ТС</a>
<a href="<?php echo $this->url(
    'vehicle',
    array('action' => 'index')
);?>">Все ТС</a>

<table class="table">
    <tr>
        <th>
            Номер транспортного средства
        </th>
        <th>
            Статус
        </th>
        <th>
            Марка / Модель
        </th>
        <th>
           Грузоподъемность
        </th>
        <th>
            Опубликовать
        </th>

        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Копировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($vehicles as $vehicle) { ?>
        <tr>
            <td>
                <?php echo $vehicle['carNumber']; ?>
            </td>
            <td>
                <?php echo $vehicle['status']; ?>
            </td>
            <td>
                <?php echo $vehicle['mark'] . ' / ' . $vehicle['model']; ?>
            </td>

            <td>
                <?php echo $vehicle['capacity']; ?>
            </td>
<td>
    <a href="<?php echo $this->url(
        'resource',
        array('action' => 'add', 'id' => $vehicle['uuid'])
    );?>">Опубликовать</a>

</td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'list', 'id' => $vehicle['uuid'])
                );?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'edit', 'id' => $vehicle['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'copy', 'id' => $vehicle['uuid'])
                );?>">Дублировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'delete', 'id' => $vehicle['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>