<?php
$vehicles = $this->res;


?>
<h1>Мои ТС</h1>
<a href="<?php echo $this->url(
    'vehicle',
    array('action' => 'add')
);?>">Добавить ТС</a>
<a href="<?php echo $this->url(
    'vehicle',
    array('action' => 'index')
);?>">Все ТС</a>

<table class="table">
    <tr>
        <th>
            Номер транспортного средства
        </th>
        <th>
            Статус
        </th>
        <th>
            Марка / Модель
        </th>
        <th>
            Грузоподъемность
        </th>
        <th>
            Опубликовать
        </th>


        <th>
            Редактировать
        </th>
        <th>
            Копировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($vehicles as $vehicle) {
        $vehicle = $vehicle['res']; ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'add', 'id' => $vehicle['uuid'], 'type' => 'list')
                ); ?>">
                    <?php echo $vehicle['carNumber']; ?>
                </a>
            </td>
            <td>
                <?php echo $vehicle['status']; ?>
            </td>
            <td>
                <?php echo $vehicle['mark'] . ' / ' . $vehicle['model']; ?>
            </td>

            <td>
                <?php echo $vehicle['capacity']; ?>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'resource',
                    array('action' => 'add', 'id' => $vehicle['uuid'])
                );?>">Опубликовать</a>

            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'add', 'id' => $vehicle['uuid'], 'type' => 'edit')
                ); ?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'add', 'id' => $vehicle['uuid'], 'type' => 'copy')
                );?>">Дублировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'delete', 'id' => $vehicle['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>