<?php
// module/Album/view/album/album/add.phtml:
$form = $this->form;
$form->setAttribute('action', $this->url('account', array('action' => 'createAccount')))
    ->prepare();
?>
<div class="orgAdd">


<?php
echo $this->form()->openTag($form);

$org = $form->get('account');
echo $this->formRow($org->get('name')->setAttributes(array( 'class' => 'form-control' )));
echo $this->formHidden($form->get('csrf')->setAttributes(array( 'class' => 'form-control' )));
echo $this->formElement($form->get('submit')->setAttributes(array( 'class' => 'form-control' )));
echo $this->form()->closeTag();
?> </div><a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
