<?php
$form = $this->form;
$form->setAttribute('action', $this->url('account', array('action' => 'add')))
    ->prepare();
?>
<div class="orgAdd">


<?php
echo $this->form()->openTag($form);

echo $this->formRow($form->get('name')->setAttributes(array( 'class' => 'form-control' )));
echo $this->formElement($form->get('submit')->setAttributes(array( 'class' => 'form-control' )));
echo $this->form()->closeTag();
?> </div><a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
