<?php
$title = 'Аккаунт';
$this->headTitle($title);
if (!empty($this->org)) {
$oc = $this->org[0];
$o = $oc['org']?>
<h1><?php echo $this->escapeHtml($title) . ' ' . $o['name']; ?></h1>
<a href="<?php echo $this->url(
    'addList',
    array('action' => 'my')
);?>">Мои справочники</a>
<table class="table">
    <tr>


        <th>Добавить админа к аккаунту</th>
        <th>Список админов</th>
        <th>Список всех юзеров аккаунта</th>
    </tr>
    <tr>

        <td><a href="<?php echo $this->url(
                'company_user',
                array('action' => 'add', 'org_id' => $o['uuid'], 'param' => 'admin')
            );?>">Добавить</a></td>
        <td><a href="<?php echo $this->url(
                'company_user',
                array('action' => 'list', 'org_id' => $o['uuid'], 'param' => 'admin')
            ); ?>">Посмотреть админов</a></td>

        <td><a href="<?php echo $this->url(
                'company_user',
                array('action' => 'list', 'org_id' => $o['uuid'], 'param' => 'user')
            ); ?>">Посмотреть юзеров</a></td>
    </tr>

</table>
<table class="table">
    <tr>
        <th>Добавить компанию</th>
        <th>Список юр. лиц</th>


    </tr>
    <tr>
        <td><a href="<?php echo $this->url(
                'company',
                array('action' => 'add', 'org_id' => $o['uuid'])
            );?>">Добавить</a></td>
        <td><a href="<?php echo $this->url('company', array('action' => 'index', 'org_id' => $o['uuid'])); ?>">Посмотреть
                юр. лица</a></td>


    </tr>

</table>


<table style="background:#ccc;" class="table">
    <tr>
        <th>Название юр. лица</th>
        <th>Юзеры юр. лица</th>
        <th>Добавить юзера в компаню</th>
        <th>Юзеры</th>
        <th>Добавть контрагента</th>
        <th>Контрагенты</th>
        <th></th>
    </tr>
    <?php foreach ($oc['com'] as $c) { ?>
        <tr>
            <td><a href="<?php echo $this->url(
                    'company',
                    array('action' => 'add', 'org_id' => $o['uuid'], 'id' => 'list', 'comId' => $c['uuid'])
                );?>"><?php echo $c['name']; ?></a></td>
            <td>
                <a href="<?php echo $this->url(
                    'company_user',
                    array('action' => 'list', 'org_id' => $c['uuid'], 'param' => 'current')
                ); ?>">Посмотреть юзеров</a></td>
            <td><a href="<?php echo $this->url(
                    'company_user',
                    array('action' => 'add', 'org_id' => $c['uuid'])
                );?>">Добавить</a></td>
            <td>
                <a href="<?php echo $this->url(
                    'company_user',
                    array('action' => 'list', 'org_id' => $c['uuid'], 'param' => 'current')
                ); ?>">Посмотреть юзеров</a></td>
            <td><a href="<?php echo $this->url(
                    'company',
                    array('action' => 'addContractAgentToCompany', 'org_id' => $c['uuid'])
                );?>">Добавить</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'contractAgentList', 'org_id' => $c['uuid'])
                ); ?>">Посмотреть контрагентов</a></td>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'add', 'id' => 'edit', 'comId' => $c['uuid'], 'org_id' => $o['uuid'])
                );?>">Редактировать</a>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'delete', 'id' => $c['uuid'], 'org_id' => $o['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
        <?php ?>

    <?php }
    } ?>

</table>
</br></br>