<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3>Hello, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[Sign Out]</a>
<div style="clear:both;"></div>
<br/><br/>
<table class='table' width='100%'>
    <tr>
        <th>
        Модуль организации
        </th>
        <th>
        Модуль ресурсы
        </th>
        <th>
        Модуль заявки
        </th>
        <th>
        Модуль аукцион
        </th>
    </tr>

<tr>
<td> <a href="<?php echo $this->url('organization', array('action'=>'index'));?>">Все организации</a>
</td>
<td>
<a href="<?php echo $this->url('resource',
    array('action'=>'index'));?>">Все ресурсы</a>
    </br>
<a href="<?php echo $this->url('resource',
    array('action'=>'my'));?>">Мои ресурсы</a></br>
<a href="<?php echo $this->url('resource',
    array('action'=>'add'));?>">Добавить ресурс</a>
</br>

   </td>
<td>
<a href="<?php echo $this->url('ticket',
    array('action'=>'index'));?>">Все заявки</a>
    </br>
<a href="<?php echo $this->url('ticket',
    array('action'=>'my'));?>">Мои заявки</a></br>
<a href="<?php echo $this->url('ticket',
    array('action'=>'add'));?>">Добавить заявку</a>
</br>
        </td>
<td>
<a href="<?php echo $this->url('auction',
    array('action'=>'index'));?>">Все аукционы</a>
</td>
</tr>
</table>