<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3>Hello, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[Sign Out]</a>
<div style="clear:both;"></div>
<br/><br/>

<a href="<?php echo $this->url('account',
    array('action'=>'add'));?>"><button type="button" class="btn btn-primary">Добавить аккаунт</button></a>