<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3>Hello, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[Sign Out]</a>
<div style="clear:both;"></div>
<br/><br/>
                <th>
                Модуль список
                </th>
</td>
<td>
<a href="<?php echo $this->url('addList',
    array('action'=>'add'));?>">Добавить список</a>