<?php
$form = $this->form;
$form->setAttribute('action', $this->url('resource', array('action' => 'addResource')))
    ->prepare();
echo $this->form()->openTag($form);

$name = $form->get('name');
///echo $this->formRow($name);

$tent = $form->get('tent');
$furgon = $form->get('furgon');
$pickup = $form->get('pickup');
$mukovoz = $form->get('mukovoz');
$mukovoz2 = $form->get('mukovoz2');

$kran = $form->get('kran');

$upSize = $form->get('upSize');
$upValue = $form->get('upValue');
$gabarities = $form->get('gabarities');
$adr = $form->get('adr');

$areaUnload = $form->get('areaUnload');
$areaLoad = $form->get('areaLoad');
$note = $form->get('note');
$currency = $form->get('currency');
$money = $form->get('money');
$formPay = $form->get('formPay');
$always = $form->get('always');
$ready = $form->get('ready');
$dateStart = $form->get('dateStart');
$dateEnd = $form->get('dateEnd');
$cycle = $form->get('cycle');

$upShip = $form->get('upShip');
$tir = $form->get('tir');
$ekmt = $form->get('ekmt');
$hydroLift = $form->get('hydroLift');

$transportType = $form->get('transportType');
?>

    <table class="table spec_table" style="">
        <tr>
            <th style="width:70%;">
                Транспорт
            </th>
            <th style="width:30%;">
                Маршрут
            </th>
        </tr>
        <tr>
            <td style="border-left:none;">
                <table class="into_table"  style="width:100%%;">
                    <tr >
                        <th>
                            Тип кузова:
                        </th>
                        <th>
                            Тип загрузки:
                        </th>
                        <th>
                            Вид транспорта:
                        </th>
                    </tr>
                    <tr>
                        <td class="tr_check">
                            <?php
                            echo $this->formRow($tent);
                            echo $this->formRow($mukovoz);
                            echo $this->formRow($mukovoz2);
                            echo $this->formRow($pickup);
                            echo $this->formRow($furgon);
                            ?>
                        </td>
                        <td class="tr_check">
                            <?php
                            echo $this->formRow($kran);
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($transportType);
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php
                            echo $this->formRow($upSize);
                            echo $this->formRow($upValue);
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($gabarities);

                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($adr);

                            ?>
                        </td>
                    </tr>
                </table>
                <div class="tr_check inline_check">
                <?php
                echo $this->formRow($upShip);
                echo $this->formRow($tir);
                echo $this->formRow($ekmt);
                echo $this->formRow($hydroLift);
                ?></div>
            </td>
            <td>
                <?php
                echo $this->formRow($areaLoad);
                echo $this->formRow($areaUnload); ?>
               <div class="tr_check">   <?php echo $this->formRow($cycle); ?></div>

            </td>
        </tr>
    </table>
    <table class="table spec_table" style>
        <tr>
            <th style="width:33%;">
                Когда
            </th>
            <th style="width:33%;">
                Оплата
            </th>
            <th style="width:33%;">
                Примечание
            </th>
        </tr>
        <tr>
            <td>
                <?php
                echo $this->formRow($dateStart);
                echo $this->formRow($dateEnd);  ?>
                <div class="tr_check"><?php
                echo $this->formRow($always);
                echo $this->formRow($ready);
                ?> </div>
            </td>
            <td>
                <?php
                echo $this->formRow($currency);
                echo $this->formRow($money);
                echo $this->formRow($formPay);
                ?>
            </td>
            <td class="note_textarea">
                <?php echo $this->formRow($note);
                ?>
            </td>
        </tr>
    </table>

<div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>