<?php
$form = $this->form;
$formWay = $this->formWay;

$form->setAttribute('action', $this->url('resource', array('action' => 'addResource')))
    ->prepare();
echo $this->form()->openTag($form);

$tsId= $form->get('tsId');
$kindOfLoad=$form->get('kindOfLoad');

$areaLoad= $formWay->get('areaLoad');
$areaUnload= $formWay->get('areaUnload');
$dateStart= $formWay->get('dateStart');
$timeStart= $formWay->get('timeStart');
$currency= $formWay->get('currency');
$money= $formWay->get('money');
$formPay= $formWay->get('formPay');
$note= $formWay->get('note');
?>

    <table class="table spec_table" style="">
        <tr>
            <th>
                Транспорт
            </th>
        </tr>
        <tr>
            <td style="border-left:none;">
                <?php
                echo $this->formRow($tsId);
                echo $this->formRow($kindOfLoad);
               ?>
            </td>
        </tr>
    </table>

    <table class="table spec_table" style="">
        <tr>
            <th>
                Маршрут
            </th>
        </tr>
        <tr>
            <td>
                <?php
                echo $this->formRow($areaLoad);
                echo $this->formRow($areaUnload);
                echo $this->formRow($dateStart);
                echo $this->formRow($timeStart);
                echo $this->formRow($currency);
                echo $this->formRow($money);
                echo $this->formRow($formPay);
                echo $this->formRow($note);
                ?>

            </td>
        </tr>
    </table>
<div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>