<?php
$form = $this->form;
$form->setAttribute('action', $this->url('resource', array('action' => 'addResource')))
    ->prepare();
echo $this->form()->openTag($form);

$name = $form->get('name')->setValue($this->res['name']);
///echo $this->formRow($name);

$tent = $form->get('tent')->setValue($this->res['tent']);
$furgon = $form->get('furgon')->setValue($this->res['furgon']);
$pickup = $form->get('pickup')->setValue($this->res['pickup']);
$mukovoz = $form->get('mukovoz')->setValue($this->res['mukovoz']);
$mukovoz2 = $form->get('mukovoz2')->setValue($this->res['mukovoz2']);

$kran = $form->get('kran')->setValue($this->res['kran']);

$upSize = $form->get('upSize')->setValue($this->res['upSize']);
$upValue = $form->get('upValue')->setValue($this->res['upValue']);
$gabarities = $form->get('gabarities')->setValue($this->res['gabarities']);
$adr = $form->get('adr')->setValue($this->res['adr']);

$areaUnload = $form->get('areaUnload')->setValue($this->res['areaUnload']);
$areaLoad = $form->get('areaLoad')->setValue($this->res['areaLoad']);
$note = $form->get('note')->setValue($this->res['note']);
$currency = $form->get('currency')->setValue($this->res['currency']);
$money = $form->get('money')->setValue($this->res['money']);
$formPay = $form->get('formPay')->setValue($this->res['formPay']);
$always = $form->get('always')->setValue($this->res['always']);
$ready = $form->get('ready')->setValue($this->res['ready']);
$dateStart = $form->get('dateStart')->setValue($this->res['dateStart']);
$dateEnd = $form->get('dateEnd')->setValue($this->res['dateEnd']);
$cycle = $form->get('cycle')->setValue($this->res['cycle']);

$upShip = $form->get('upShip')->setValue($this->res['upShip']);
$tir = $form->get('tir')->setValue($this->res['tir']);
$ekmt = $form->get('ekmt')->setValue($this->res['ekmt']);
$hydroLift = $form->get('hydroLift')->setValue($this->res['hydroLift']);

$transportType = $form->get('transportType')->setValue($this->res['transportType']);
?>

    <table class="table spec_table" style="">
        <tr>
            <th style="width:70%;">
                Транспорт
            </th>
            <th style="width:30%;">
                Маршрут
            </th>
        </tr>
        <tr>
            <td style="border-left:none;">
                <table class="into_table"  style="width:100%%;">
                    <tr>
                        <th>
                            Тип кузова:
                        </th>
                        <th>
                            Тип загрузки:
                        </th>
                        <th>
                            Вид транспорта:
                        </th>
                    </tr>
                    <tr>
                        <td class="tr_check">
                            <?php
                            echo $this->formRow($tent);
                            echo $this->formRow($mukovoz);
                            echo $this->formRow($mukovoz2);
                            echo $this->formRow($pickup);
                            echo $this->formRow($furgon);
                            ?>
                        </td>
                        <td class="tr_check">
                            <?php
                            echo $this->formRow($kran);
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($transportType);
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php
                            echo $this->formRow($upSize);
                            echo $this->formRow($upValue);
                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($gabarities);

                            ?>
                        </td>
                        <td>
                            <?php
                            echo $this->formRow($adr);

                            ?>
                        </td>
                    </tr>
                </table>
                <div class="tr_check inline_check">
                    <?php
                    echo $this->formRow($upShip);
                    echo $this->formRow($tir);
                    echo $this->formRow($ekmt);
                    echo $this->formRow($hydroLift);
                    ?></div>
            </td>
            <td>
                <?php
                echo $this->formRow($areaLoad);
                echo $this->formRow($areaUnload); ?>
                <div class="tr_check">   <?php echo $this->formRow($cycle); ?></div>

            </td>
        </tr>
    </table>
    <table class="table spec_table" style>
        <tr>
            <th style="width:33%;">
                Когда
            </th>
            <th style="width:33%;">
                Оплата
            </th>
            <th style="width:33%;">
                Примечание
            </th>
        </tr>
        <tr>
            <td>
                <?php
                echo $this->formRow($dateStart);
                echo $this->formRow($dateEnd);  ?>
                <div class="tr_check"><?php
                    echo $this->formRow($always);
                    echo $this->formRow($ready);
                    ?> </div>
            </td>
            <td>
                <?php
                echo $this->formRow($currency);
                echo $this->formRow($money);
                echo $this->formRow($formPay);
                ?>
            </td>
            <td class="note_textarea">
                <?php echo $this->formRow($note);
                ?>
            </td>
        </tr>
    </table>

    <div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>