<?php
$resources = $this->res;

$types_r = array('Тентовый' => 'tent', 'Фургон' => 'furgon', 'Пикап' => 'pickup', 'Муковоз' => 'mukovoz');
?>
<a href="<?php echo $this->url(
    'resource',
    array('action' => 'add')
);?>">Добавить ресурс</a>
<a href="<?php echo $this->url(
    'resource',
    array('action' => 'index')
);?>">Все ресурсы</a>

<table class="table">
    <tr>
        <th>
            Типы перевозок
        </th>
        <th>
            Дата отрпавления / Прибытия
        </th>
        <th>
            Стоимость
        </th>
        <th>
            ТС
        </th>
        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Добавить аукцион
        </th>
        <th>
            Копировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($resources as $resource) {
        $vehicle=$resource['veh'];
        $resource=$resource['res'];

        ?>
        <tr>
            <td>
                <?php foreach ($types_r as $key => $value) {
                    echo $key . ' ' . $resource[$value] . ' ';
                }
                ?>
            </td>
            <td>
                <?php echo $resource['dateStart'] . ' / ' . $resource['dateEnd']; ?>
            </td>
            <td>
                <?php echo $resource['money'] . ' ' . $resource['currency']; ?>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'vehicle',
                    array('action' => 'list', 'id' => $vehicle['uuid'])
                );?>"><?php echo $vehicle['carNumber'].' '.$vehicle['mark'] . ' / ' . $vehicle['model']; ?></a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'resource',
                    array('action' => 'list', 'id' => $resource['uuid'])
                );?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'resource',
                    array('action' => 'edit', 'id' => $resource['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'auction',
                    array('action' => 'add', 'id' => $resource['uuid'])
                );?>">Добавить аукцион</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'resource',
                    array('action' => 'copy', 'id' => $resource['uuid'])
                );?>">Копировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'resource',
                    array('action' => 'delete', 'id' => $resource['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>