<?php
$form = $this->form;
$formWay = $this->formWay;

$form->setAttribute('action', $this->url('resource', array('action' => 'getResult')))
    ->prepare();
echo $this->form()->openTag($form);

$tsId = $form->get('tsId')->setAttributes(array('required' => ''));
$typeLoad = $form->get('typeLoad')->setAttributes(array('required' => ''));

$areaLoad = $formWay->get('areaLoad')->setAttributes(array('required' => ''));
$areaUnload = $formWay->get('areaUnload')->setAttributes(array('required' => ''));
$dateStart = $formWay->get('dateStart')->setAttributes(array('required' => ''));
$timeStart = $formWay->get('timeStart')->setAttributes(array('required' => ''));
$currency = $formWay->get('currency')->setAttributes(array('required' => ''));
$money = $formWay->get('money')->setAttributes(array('required' => ''));
$formPay = $formWay->get('formPay')->setAttributes(array('required' => ''));
$note = $formWay->get('note')->setAttributes(array('required' => ''));
?>
    <h1>Поиск по ресурсам</h1>
    <p><b>Впишите поля, по которым будет вестись поиск. Пустые поля будут пропущены.</b></p>
    <table class="table spec_table" style="">
        <tr>
            <th>

            </th>
        </tr>
        <tr>
            <td style="border-left:none;">
                <?php
                //   echo $this->formRow($tsId);
                //  echo $this->formRow($typeLoad);
                ?>
            </td>
        </tr>
    </table>

    <table class="table spec_table" style="">
        <tr>
            <th>
                Маршрут
            </th>
            <th>
                Дата и время загрузки
            </th>
            <th>
                Оплата
            </th>
            <th>
                Примечание
            </th>
            <th>
                Удалить пункт выдачи
            </th>

        </tr>
        <tr class="wayTr">
            <td>
                <?php
                echo $this->formRow($areaLoad);
                echo $this->formRow($areaUnload);
                ?>
            </td>
            <td>
                <?php
                echo $this->formRow($dateStart);
                echo $this->formRow($timeStart);
                ?>
            </td>
            <td>
                <?php
                echo $this->formRow($currency);
                echo $this->formRow($money);
                echo $this->formRow($formPay);
                ?>
            </td>
            <td>
                <?php
                echo $this->formRow($note);
                ?>
            </td>
            <td>
                <input name="deleteWay" class="deleteWay" type="button" value="Удалть"/>
            </td>
        </tr>
        <tr class="addTr">
            <td>
                <input id="counter" type="hidden" value='0'/>

            </td>
        </tr>
    </table>
    <div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>