<?php

$form = $this->form;
$param=$this->param;
$comContractUuid=$this->comContractUuid;
$form->setAttribute('action', $this->url('company', array('action' => 'createCompany', 'org_id' => $this->org_id,'id'=>$param, 'comId'=>$comContractUuid)))
    ->prepare();

$name=$form->get('name');
$shortName=$form->get('shortName');
$ogrn=$form->get('ogrn');
$inn=$form->get('inn');
$kpp=$form->get('kpp');
$taxNumber=$form->get('taxNumber');
$dateStart=$form->get('dateStart');
$address=$form->get('address');
$contact=$form->get('contact');
$createWay=$form->get('createWay');
$dateRegistration=$form->get('dateRegistration');
$nalogNumber=$form->get('nalogNumber');
$capitalValue=$form->get('capitalValue');
$founderCount=$form->get('founderCount');
$founder=$form->get('founder');
$authorizedPerson=$form->get('authorizedPerson');
$okved=$form->get('okved');
$insuranceNumberInPfr=$form->get('numberInPfr');
$numberInPfr=$form->get('numberInPfr');
$dateRegistrationPfr=$form->get('dateRegistrationPfr');
$insuranceNumberFms=$form->get('insuranceNumberFms');
$numberInFms=$form->get('numberInFms');
$dateRegistrationFms=$form->get('dateRegistrationFms');
$license=$form->get('license');
$applicants=$form->get('applicants');
$taxSystem=$form->get('taxSystem');
$taxPercent=$form->get('taxPercent');
$egrulLink=$form->get('egrulLink');
$law=$form->get('law');
$documents=$form->get('documents');
$bankAccount=$form->get('bankAccount');
$accountantLink=$form->get('accountantLink');
$anotherPersons=$form->get('anotherPersons');
$websites=$form->get('websites');

echo $this->form()->openTag($form);
?>
<h1>Добавление компании</h1>
<div class="companyAdd">
    <table class="table" style="width: 100%">

        <tr>
            <td width='50%'>
                <?php
                     echo $this->formRow($name);
                    echo $this->formRow($shortName);
                    echo $this->formRow($ogrn);
                    echo $this->formRow($inn);
                    echo $this->formRow($kpp);
                    echo $this->formRow($taxNumber);
                    echo $this->formRow($dateStart);
                ?>
                <div class="address">
                    <?php
                    echo '<h1>'.$address->getLabel().'</h1>';
                    echo '<div class="template">'.$this->formCollection($address->getTemplateElement()).'</div>';
                    foreach($address as $collectionForm) {
                        echo '<fieldset>'.$this->formCollection($collectionForm).'</fieldset>';
                    } ?>
                </div>
                <button type="button" onclick="addItem('address');">Добавить еще адресс</button>
                <div class="authorizedPerson">
                    <?php
                    echo '<h1>'.$authorizedPerson->getLabel().'</h1>';
                    echo '<div class="template">'.$this->formCollection($authorizedPerson->getTemplateElement()).'</div>';
                    foreach($authorizedPerson as $collectionForm) {
                        echo '<fieldset>'.$this->formCollection($collectionForm).'</fieldset>';
                    } ?>
                </div>
                <button type="button" onclick="addItem('authorizedPerson');">Добавить уполномоченное лицо</button>


            </td>
            <td width='50%'>
                <div class="contact">
                    <?php
                    echo '<h1>'.$contact->getLabel().'</h1>';
                    echo '<div class="template">'.$this->formCollection($contact->getTemplateElement()).'</div>';
                    foreach($contact as $collectionForm) {
                        echo '<fieldset>'.$this->formCollection($collectionForm).'</fieldset>';
                    } ?>
                </div>
                <button type="button" onclick="addItem('contact');">Добавить контакт</button>
                <?php
                echo $this->formRow($createWay);
                echo $this->formRow($dateRegistration);
                echo $this->formRow($nalogNumber);
                echo $this->formRow($capitalValue);
                echo $this->formRow($founderCount);
                ?>
                <div class="founder">
                    <?php
                    echo '<h1>'.$founder->getLabel().'</h1>';
                    echo '<div class="template">'.$this->formCollection($founder->getTemplateElement()).'</div>';
                    foreach($founder as $collectionForm) {
                        echo '<fieldset>'.$this->formCollection($collectionForm).'</fieldset>';
                    } ?>
                </div>
                <button type="button" onclick="addItem('founder');">Добавить основателя</button>

                <div class="okved">
                    <?php
                    echo '<h1>'.$okved->getLabel().'</h1>';
                    echo '<div class="template">'.$this->formCollection($okved->getTemplateElement()).'</div>';
                    foreach($okved as $collectionForm) {
                        echo '<fieldset>'.$this->formCollection($collectionForm).'</fieldset>';
                    } ?>
                </div>
                <button type="button" onclick="addItem('okved');">Добавить код ОКВЭД</button>
                <?php
                    echo $this->formRow($insuranceNumberInPfr);
                    echo $this->formRow($numberInPfr);
                    echo $this->formRow($dateRegistrationPfr);
                    echo $this->formRow($insuranceNumberFms);
                    echo $this->formRow($numberInFms);
                    echo $this->formRow($dateRegistrationFms);
                ?>
            </td>
        </tr>

        <tr>
            <td width='50%'>
                $license=$form->get('license');
                <?php
                echo $this->formRow($taxSystem);
                echo $this->formRow($taxPercent);
                echo $this->formRow($egrulLink);
                ?>
                $documents=$form->get('documents');
                $bankAccount=$form->get('bankAccount');

                <?php
                $accountantLink=$form->get('accountantLink');
                ?>
                $websites=$form->get('websites');

            </td>
            <td width='50%'>
                $applicants=$form->get('applicants');
                $law=$form->get('law');
                $anotherPersons=$form->get('anotherPersons');
            </td>
        </tr>

        <tr>
            <td width='50%'>

            </td>
            <td width='50%'>

            </td>
        </tr>

    </table>
    <script>
        function addItem(item) {
            var currentCount = $('.'+item+' .counter').val();
            if(typeof currentCount=== 'undefined') {
                $('.'+item).append("<input type='hidden' class='counter' value='1'>");
                currentCount=1;
            }
            var template=$('.'+item+' .template').html();
            template = template.replace(/__index__/g, currentCount);

            $('.'+item).append('<fieldset>'+template+'</fieldset>');
            currentCount++;
            $('.'+item+' .counter').val(currentCount);
        }
        function deleteFieldset(element) {
            var conf = confirm('Вы действительно хотите удалить элемент?');
            if (!conf) {
                return false;
            }
            else {
                $(element).parent().remove();
            }

        }

    </script>

    <?php


echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>

<?php

?> <a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
