<?php

$form = $this->form;
$param=$this->param;
$comContractUuid=$this->comContractUuid;
$form->setAttribute('action', $this->url('company', array('action' => 'createCompany', 'org_id' => $this->org_id,'id'=>$param, 'comId'=>$comContractUuid)))
    ->prepare();

echo $this->form()->openTag($form);
//$whoGave= $form->get('whoGave');
//echo $this->formRow($serialNumber);
?>
<div class="companyAdd">
<?php


echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('property'));
echo $this->formRow($form->get('generalManager'));
echo $this->formRow($form->get('official'));
echo $this->formRow($form->get('chiefAccountant'));
echo $this->formRow($form->get('note'));
//echo $this->formRow($form->get('addressFact'));
//echo $this->formRow($form->get('addressReg'));
echo  $this->formElement($form->get('address'));
echo $this->formRow($form->get('requisites'));
echo $this->formRow($form->get('inn'));
echo $this->formRow($form->get('kpp'));
echo $this->formRow($form->get('okv'));
echo $this->formRow($form->get('personal'));

echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>

<?php

?> <a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
