<?php
$agents=$this->agents;
$com=$this->com;
?>
<h1>Контрагенты компании <?php echo $com['property'].' '.$com['name'];?></h1>

<a href="<?php echo $this->url('account', array('action' => 'index')); ?>">Вернуться в аккаунт</a>
<table  class="table">
    <tr>
        <th>Название контрагента</th>
        <th></th>
    </tr>
    <?php foreach($agents as $c) {  ?>
        <tr>
            <td><a href="<?php echo $this->url('company',
                    array('action'=>'list', 'org_id'=>$c['uuid'],'id' => $c['uuid']));?>"><?php echo $c['property'].' '.$c['name']; ?></a></td>
        </tr>


    <?php }  ?>

</table>