<?php

$displayName = $this->zfcUserIdentity() ? $this->zfcUserIdentity()->getDisplayname() : '';

echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Карго')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => '/image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
        )
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile(
        $this->basePath() . '/js/html5.js',
        'text/javascript',
        array('conditional' => 'lt IE 9',)
    )
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/ready.js')
        ->prependFile('http://code.jquery.com/jquery-2.0.0.min.js')
        ->prependFile($this->basePath() . '/js/addWay.js')

    ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->url('home') ?>">Грузоперевозки</a>

            <div class="nav-collapse collapse">
                <?php
                echo $this->navigation('topmenu_navigation')->menu()->setPartial('application/layout/top-menu');
                ?>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div id="login-form"
     class="modal hide fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="LoginFormLabel"
     aria-hidden="true">
    <?php echo $this->zfcUserLoginWidget(); ?>
</div>
<div class="container">
    <?php if ($this->zfcUserIdentity()) { ?>
    <div class="row">
        <div class="span2">
            <?php
            echo $this->navigation('sidebar_navigation')->menu()->setPartial(null)->setUlClass('nav nav-list');
            ?>
                <a href="/addList/my-fields/2258f8bc165842a48c6dd2c6f0a2157b">
                    ТС - марка
                </a></br>
                <a href="/addList/my-fields/b3c8ad8bd32e4d8fb439a4c09b7edd75">
                    ТС - модель
                </a></br>
                <a href="/addList/my-fields/21a05595304a451da912652a816de645">
                    ТС - статус
                </a></br>
                <a href="/addList/my-fields/f7f0fbb3be874011969ae0e4322d5a37">
                    ТС - тип
                </a></br>
                <a href="/addList/my-fields/56034bc8b49d4f05a094c142363a94ab">
                    Компания - Форма собственности
                </a></br>
                <a href="/addList/my-fields/1c25bf22c7514891a2ed6ab19452c4f6">
                    Компания - Реквизиты
                </a></br>
                <a href="/addList/my-fields/a04f1b475c6648f195d4f0978dccd1fa">
                    Заявка - груз
                </a></br>
                <a href="/addList/my-fields/83917605d9bc450e9c1da9ee03ef0cc0">
                    Заявка - тип загрузки
                </a></br>
                <a href="/addList/my-fields/6c455e756a0943afb90b22187dfc5c07">
                    Заявка -тип выгрузки
                </a></br>
                <a href="/addList/my-fields/105863b25e1046c68fa69289f182da7e">
                    Заявка - тип ТС
                </a></br>
                <a href="/addList/my-fields/c83043049ac946aba1d358a1c4eb5a1b">
                    Предложения - статус
                </a></br>

        </div>
        <div class="span10">
            <?php echo $this->content; ?>
        </div>
    </div>
    <?php } else { ?>
        <?php echo $this->content; ?>
    <?php } ?>
</div>
<!-- /container -->
<footer class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <span class="brand" href="#">&copy;&nbsp;2013&nbsp;СП Онлайн</span>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>