<?php

$displayName = $this->zfcUserIdentity() ? $this->zfcUserIdentity()->getDisplayname() : '';

echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Карго')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => '/image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
        )
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile(
        $this->basePath() . '/js/html5.js',
        'text/javascript',
        array('conditional' => 'lt IE 9',)
    )
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/ready.js')
        ->prependFile('http://code.jquery.com/jquery-2.0.0.min.js')

    ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->url('home') ?>">Грузоперевозки</a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>">Главная</a></li>
                    <li class="active"><a href="/user"><?php echo $this->translate(
                                'Личный кабинет'
                            ) ?></a></li>
                </ul>
                <ul class="nav pull-right">
                    <?php if (!$this->zfcUserIdentity()): ?>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/register') ?>">
                                Регистрация
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/login') ?>"
                               class="js"
                               data-event="click"
                               data-handler="App.Login.dialog"
                               data-content="#login-form">
                                Войти&nbsp;<i class="icon-off icon-white"></i>
                            </a>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?php echo $this->url('zfcuser') ?>">
                                <i class="icon-user icon-white"></i>&nbsp;<?php echo $displayName; ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/logout') ?>">
                                Выйти&nbsp;<i class="icon-off icon-white"></i>
                            </a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div id="login-form"
     class="modal hide fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="LoginFormLabel"
     aria-hidden="true">
    <?php echo $this->zfcUserLoginWidget(); ?>
</div>
<div class="container">
    <?php if ($this->zfcUserIdentity()) { ?>
    <div class="row">
        <div class="span2">
            <ul class="nav nav-list">
                <li><a href="<?php echo $this->url('organization', array('action'=>'index'));?>">Аккаунт</a></li>
                <li class="nav-header">Органищация</li>
                <li><a href="<?php echo $this->url('organization', array('action' => 'index'));?>">Моя организация</a></li>
                <li class="nav-header">Рерусы</li>
                <li><a href="<?php echo $this->url('resource', array('action' => 'index'));?>">Все ресурсы</a></li>
                <li><a href="<?php echo $this->url('resource', array('action' => 'my'));?>">Мои ресурсы</a></li>
                <li><a href="<?php echo $this->url('resource', array('action' => 'add'));?>">Добавить ресурс</a></li>
                <li class="nav-header">ТС</li>
                <li><a href="<?php echo $this->url('vehicle', array('action' => 'index'));?>">Все ТС</a></li>
                <li><a href="<?php echo $this->url('vehicle', array('action' => 'my'));?>">Мои ТС</a></li>
                <li><a href="<?php echo $this->url('vehicle', array('action' => 'add'));?>">Добавить ТС</a></li>
                <li class="nav-header">Заявки</li>
                <li><a href="<?php echo $this->url('ticket', array('action' => 'index'));?>">Все заявки</a></li>
                <li><a href="<?php echo $this->url('ticket', array('action' => 'my'));?>">Мои заявки</a></li>
                <li><a href="<?php echo $this->url('ticket', array('action' => 'add'));?>">Добавить заявку</a></li>
                <li class="nav-header">Аукцион</li>
                <li><a href="<?php echo $this->url('auction', array('action' => 'my'));?>">Аукционы</a></li>
                <li class="nav-header">Список</li>
                <li><a href="<?php echo $this->url('addList', array('action' => 'my'));?>">Мои списки</a></li>
                <li><a href="<?php echo $this->url('addList', array('action' => 'add'));?>">Добавить список</a></li>
            </ul>
        </div>
        <div class="span10">
            <?php echo $this->content; ?>
        </div>
    </div>
    <?php } else { ?>
        <?php echo $this->content; ?>
    <?php } ?>
</div>
<!-- /container -->
<footer class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <span class="brand" href="#">&copy;&nbsp;2013&nbsp;СП Онлайн</span>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>