<?php
$title = 'Компании добавленные в контрагенты';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
    <tr>
        <th>Название юр. лица</th>
        <th>Объеденить</th>
        <th>Утвердить</th>
        <th>Заблокировать</th>
    </tr>
    <?php foreach ($this->com as $c) { ?>

        <tr>
            <td><a href="<?php echo $this->url(
                    'company',
                    array('action' => 'list', 'id' => $c['uuid'])
                );?>"><?php echo $c['name']; ?></a></td>
            <td></td>
            <td></td>
            <td><a href="<?php echo $this->url(
                    'company_user',
                    array('action' => 'add', 'org_id' => $c['uuid'])
                );?>">Добавить</a></td>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'edit', 'id' => $c['uuid'])
                );?>">Редактировать</a>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'delete', 'id' => $c['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>


    <?php } ?>

</table>
