<?php
$title = 'Компании добавленные в контрагенты';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
    <tr>
        <th>Название юр. лица</th>
        <th>Объеденить</th>
        <th>Утвердить</th>
        <th>Заблокировать</th>
    </tr>
    <?php foreach ($this->com as $c) { ?>

        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'add', 'org_id' => 'contractAgent', 'id' => 'list', 'comId' => $c['uuid'])
                );?>"><?php echo $c['name']; ?></a>
            </td>

            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'adminContractAgentUnity', 'id'=>$c['uuid'],'org_id' => 'unity')
                );?>">Объеденить</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'adminContractAgent', 'id'=>$c['uuid'],'org_id' => 'approve')
                );?>">Утвердить</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'company',
                    array('action' => 'adminContractAgent', 'id'=>$c['uuid'],'org_id' => 'block')
                );?>">Заблокировать</a>
            </td>

        </tr>


    <?php } ?>

</table>
