<?php
$contracts = $this->contract;

?>
<h1>Заявки/ресурсы работе</h1>
<table class="table" width="100%">
    <tr>
        <th>
            Номер предложения (просмотр истории предложения)
        </th>
        <th>
            Для чего предложили
        </th>
        <th>
            Что предложили
        </th>

        <th>
            Статус
        </th>

    </tr>
    <?php foreach ($contracts as $contract) { ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'contract',
                    array('action' => 'proposal', 'id' => $contract['uuid'])
                );?>">
                    <?php echo $contract['uuid']; ?>
                </a>
            </td>
            <td>

                <a href="<?php

                if ($contract['sendItem']['status'] == 'Заявка') {
                    $rout = 'ticket';
                } else {
                    $rout = 'resource';
                }
                echo $this->url(
                    $rout,
                    array('action' => 'add', 'type' => 'list', 'id' => $contract['sendItem']['uuid'])
                );?>">
                    <?php echo $contract['sendItem']['uuid'] . '(' . $contract['sendItem']['status'] . ')'; ?>
                </a>
            </td>
            <td>

                <a href="<?php

                if ($contract['receiveItem']['status'] == 'Заявка') {
                    $rout = 'ticket';
                } else {
                    $rout = 'resource';
                }
                echo $this->url(
                    $rout,
                    array('action' => 'add', 'type' => 'list', 'id' => $contract['receiveItem']['uuid'])
                );?>">
                    <?php echo $contract['receiveItem']['uuid'] . '(' . $contract['receiveItem']['status'] . ')'; ?>
                </a>
            </td>
            <td>
                <?php echo $contract['status']; ?>
            </td>
        </tr>
    <?php } ?>
</table>
