<?php
$notes = $this->notification;
?>
<table class="table">
    <tr>
        <th>Номер Item</th>
        <th>Компания Владелец</th>
        <th>Ваше последнее примечани</th>
        <th>Статус</th>
        <th>Рассмотреть заявку</th>
    </tr>
    <?php
    foreach ($notes as $note) {
        $owner = $note['owner'];
        $nt = $note['notes'];
        $note = $note['item'];

        ?>
        <tr>
            <td><a href="<?php
                if ($note['type'] == 'Ресурс') {
                    $type = 'resource';
                } elseif ($note['type'] == 'Заявка') {
                    $type = 'ticket';
                } else {
                    $type = 'vehicle';
                }

                echo $this->url(
                    $type,
                    array('action' => 'add', 'type' => 'edit', 'id' => $note['itemId'])
                );?>"><?php echo $note['itemId'] . ' (' . $note['type'] . ')'; ?></a>
            </td>
            <td><?php echo $owner['property'] . ' ' . $owner['name']; ?></td>
            <td><?php if (!empty($nt[count($nt) - 1]['note'])) {
                    echo $nt[count($nt) - 1]['note'];
                } ?></td>
            <td><?php
                if (!empty($note['status'])) {
                    echo $note['status'];
                } else {
                    echo "Вы еще не рассмотрели данную заявку";
                }


                ?></td>
            <td><a href="<?php echo $this->url(
                    'notification',
                    array('action' => 'add', 'id' => $note['uuid'])
                );?>">Рассмотерть</a></td>
        </tr>
    <?php
    }
    ?>
</table>