<?php
$notifications=$this->notification;

?>
<h1>Полученные предложения</h1>
<table class="table" width="100%">
    <tr>
        <th>
            Номер предложения (просмотр истории предложения)
        </th>
        <th>
            Для чего предложили
        </th>
        <th>
            Что предложили
        </th>
        <th>
            Статус
        </th>

    </tr>
    <?php foreach($notifications as $notification) { ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('notification',
                    array('action'=>'proposal', 'id' => $notification['uuid']));?>">
                    <?php echo $notification['uuid'];?>
                </a>
            </td>
            <td>

                <a href="<?php

                if($notification['sendItem']['status']=='Заявка') {
                    $rout='ticket';
                } else {
                    $rout='resource';
                }
                echo $this->url($rout,
                    array('action'=>'list', 'id' => $notification['sendItem']['uuid']));?>">
                    <?php echo $notification['sendItem']['uuid'].'('.$notification['sendItem']['status'].')';?>
                </a>
            </td>
            <td>

                <a href="<?php

                if($notification['receiveItem']['status']=='Заявка') {
                    $rout='ticket';
                } else {
                    $rout='resource';
                }
                echo $this->url($rout,
                    array('action'=>'list', 'id' => $notification['receiveItem']['uuid']));?>">
                    <?php echo $notification['receiveItem']['uuid'].'('.$notification['receiveItem']['status'].')';?>
                </a>
            </td>
            <td>
                <?php echo $notification['status']; ?>
            </td>
        </tr>
    <?php } ?>
</table>
