<?php
$id=$this->id;
$form = $this->form;
$form->setAttribute('action', $this->url('excel', array('action' => 'generateTemplate', 'id'=>$id)))
    ->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('type')->setAttributes(array( 'class' => 'form-control' )));
echo $this->formRow($form->get('file')->setAttributes(array( 'class' => 'form-control' )));
echo $this->formElement($form->get('submit')->setAttributes(array( 'class' => 'form-control' )));
echo $this->form()->closeTag();
?>

