<?php
$form = $this->form;
$formWay = $this->formWay;
$formVehicle=$this->formVehicle;

$form->setAttribute('action', $this->url('ticket', array('action' => 'add')))
    ->prepare();
echo $this->form()->openTag($form);


$areaLoad= $formWay->get('areaLoad');
$areaUnload= $formWay->get('areaUnload');

$cargoOwner= $formWay->get('cargoOwner');
$cargoName= $formWay->get('cargoName');

$adr= $formWay->get('adr');
$cubs= $formWay->get('cubs');
$dimensions= $formWay->get('dimensions');
$weight= $formWay->get('weight');
$rubles= $formWay->get('rubles');
$pallet= $formWay->get('pallet');
$box= $formWay->get('box');

$type= $formVehicle->get('type');

$temperature= $formWay->get('temperature');

$typeLoad= $formWay->get('typeLoad');

$typeUnload=clone $formWay->get('typeLoad');
$typeUnload= $typeUnload->setName('typeUnload')->setOptions(array("label"=>'Тип выгрузки'));



$airSuspension= $formWay->get('airSuspension');
$coupling= $formWay->get('coupling');

$dateStart= $formWay->get('dateStart');
$timeStart= $formWay->get('timeStart');
$dateEnd= $formWay->get('dateEnd');
$timeEnd= $formWay->get('timeEnd');

$currency= $form->get('currency');
$money= $form->get('money');
$formPay= $form->get('formPay');
$typeTicket= $form->get('typeTicket');


$note= $formWay->get('note');

$docNumber = $formWay->get('docNumber');
$docWay = $formWay->get('docWay');
$docNote = $formWay->get('docNote');
$docDate = $formWay->get('docDate');
$docType= $formWay->get('docType');


?>

    <table class="table spec_table" style="">
        <tr>
            <th>
               Заявка
            </th>
        </tr>
        <tr>
            <td style="border-left:none;">
                <?php
                echo $this->formRow($currency);
                echo $this->formRow($money);
                echo $this->formRow($formPay);
                echo $this->formRow($typeTicket);
                ?>
            </td>
        </tr>
    </table>

    <table class="table spec_table" style="">
        <tr>
            <th>
                Маршрут
            </th>
            <th>
                Данные груза
            </th>
            <th>
               Количество груза
            </th>
            <th>
                Требования к ТС
            </th>
            <th>
                Время
            </th>
            <th>
                Документы к грузу

            </th>
            <th>
                Примечание
            </th>
            <th>
                Удалить пункт выдачи
            </th>

        </tr>
        <tr class="wayTr">
            <td>
                <?php
                echo $this->formRow($areaLoad);
                echo $this->formRow($areaUnload);
                ?>
            </td>
            <td>
                <?php
                echo $this->formRow($cargoOwner);
                echo $this->formRow($cargoName);
                echo $this->formRow($adr);

                ?>
            </td>
            <td>
                <?php
                echo $this->formRow( $adr);
                echo $this->formRow( $cubs);
                echo $this->formRow(  $dimensions);
                echo $this->formRow(  $weight);
                echo $this->formRow(  $rubles);
                echo $this->formRow(  $pallet);
                echo $this->formRow( $box);

                ?>
            </td>
            <td>
                <?php
                echo $this->formRow( $type);
                echo $this->formRow($temperature);
                ?>
<div class="muliboxTicket">
                <?php
                echo $this->formRow( $typeLoad);

                echo $this->formRow( $typeUnload);
                ?>
</div>
                <?php
                echo $this->formRow( $airSuspension);
                echo $this->formRow( $coupling);
                ?>
            </td>
            <td>
                <?php
                echo $this->formRow($dateStart);
                echo $this->formRow($timeStart);
                echo $this->formRow($dateEnd);
                echo $this->formRow($timeEnd);
                ?>
            </td>
<td>
    <?php
    echo $this->formRow($docNumber);
    echo $this->formRow($docWay );
    echo $this->formRow($docNote );
   echo $this->formRow($docDate );
   echo $this->formRow($docType);
    ?>
</td>
            <td>
                <?php
                echo $this->formRow($note);
                ?>
            </td>

            <td>
                <input name="deleteWay" class="deleteWay" type="button" value="Удалть"/>
            </td>
        </tr>
        <tr class="addTr">
            <td>
                <input id="counter" type="hidden" value='0' />
                <input type="button" onclick="addWay('wayTr');" value="Добавить пункт назначения "/>
            </td>
        </tr>
    </table>
<div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>