<?php
$tickets=$this->res;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>

<h1>Все заявки</h1>


<table class="table">
    <tr>
        <th>
Номер заявки
        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>
            Организация
        </th>


         <th>
             Добавить аукцион
          </th>
          <th>
          Предложить ресурс
          </th>

    </tr>
    <?php foreach ($tickets as $ticket) {
    $ticketWay=$ticket['ways'];
    $cargo=$ticket['veh'];
    $org=$ticket['org'];
    $ticket=$ticket['res'];

    ?>
<tr>
            <td>
                 <a href="<?php echo $this->url(
                                    'ticket',
                                    array('action' => 'add', 'id' => $ticket['uuid'] ,'type'=>'list')
                                );?>"><?php echo $ticket['uuid']; ?></a>
            </td>
            <td>

            </td>
            <td>


            </td>
            <td>

            </td>

            <td>

            </td>
            <td>

            </td>
            <td>

            </td>
        <td>
        <a href="<?php echo $this->url('organization',
                    array('action'=>'list', 'id' => $org['uuid']));?>"><?php echo $org['name']; ?></a>
        </td>

        <td>
            <a href="<?php echo $this->url('auction',
                array('action'=>'add', 'id' => $ticket['uuid']));?>">Добавить аукцион</a>
        </td>
                     <td>
                            <a href="<?php echo $this->url('interaction',
                                array('action'=>'add', 'id' => $ticket['uuid']));?>">Добавить предложение</a>
                        </td>

</tr>
    <?php } ?>

</table>