<?php
$tickets=$this->res;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>


<a href="<?php echo $this->url('ticket',
    array('action'=>'add'));?>">Добавить ресурс</a>
<a href="<?php echo $this->url('ticket',
    array('action'=>'my'));?>">Мои ресурсы</a>

<table class="table">
    <tr>
        <th>
Номер заявки
        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>
            Организация
        </th>

         <th>
             Редактировать
          </th>
         <th>
             Добавить аукцион
          </th>

    </tr>
    <?php foreach ($tickets as $ticket) {
    $ticketWay=$ticket['ways'];
    $cargo=$ticket['veh'];
    $org=$ticket['org'];
    $ticket=$ticket['res'];

    ?>
<tr>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'list', 'id' => $ticket['uuid'])
                );?>"><?php echo $ticket['uuid']; ?></a>
            </td>
            <td>

            </td>
            <td>


            </td>
            <td>

            </td>

            <td>

            </td>
            <td>

            </td>
            <td>

            </td>
        <td>
        <a href="<?php echo $this->url('organization',
                    array('action'=>'list', 'id' => $org['uuid']));?>"><?php echo $org['name']; ?></a>
        </td>
        <td>
            <a href="<?php echo $this->url('ticket',
                array('action'=>'edit', 'id' => $ticket['uuid']));?>">Редактировать</a>
        </td>
        <td>
            <a href="<?php echo $this->url('auction',
                array('action'=>'add', 'id' => $ticket['uuid']));?>">Добавить аукцион</a>
        </td>

</tr>
    <?php } ?>

</table>