<?php
$tickets = $this->res;

$types_r = array('Тентовый' => 'tent', 'Фургон' => 'furgon', 'Пикап' => 'pickup', 'Муковоз' => 'mukovoz');
?>
<h1>Заявки моего аккаунта</h1>


<table class="table">
    <tr>
        <th>
            Номер заявки
        <th>

        </th>
        <th>

        </th>
        <th>

        </th>
        <th>
            Прикрепленый ресурс
        </th>
        <th>
            Печать счета
        </th>
        <th>
            Статус (Глобальный)
        </th>
        <th>
            Статус (Рабочий)
        </th>
        <th>
            Компания
        </th>
        <th>
            Печать
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Предложить ресурс
        </th>
        <th>
            Копировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($tickets as $ticket) {
        $ticketWay = $ticket['ways'];
        $cargo = $ticket['veh'];
        $owner = $ticket['owner'];
        $acceptedResource = $ticket['acceptedResource'];
        $ticket = $ticket['res'];

        ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'add', 'id' => $ticket['uuid'], 'type' => 'list')
                );?>"><?php echo $ticket['numberInt']; ?></a>
            </td>
            <td>

            </td>
            <td>


            </td>
            <td>

            </td>

            <td>
                <?php
                if (!empty($acceptedResource)) {
                    $vehicle = $acceptedResource['veh'];
                    $owner = $acceptedResource['owner'];
                    $resource = $acceptedResource['res'];

                    ?>
                    <?php echo $owner['property'] . ' ' . $owner['name'] . ' '; ?>
                    <?php
                    $str = '';
                    if (!empty($vehicle['semitrailer'])) {
                        $str .= 'Полуприцеп ';
                    }
                    if (!empty($vehicle['tractor'])) {
                        $str .= 'Тягач ';
                    }
                    if (!empty($vehicle['coupling'])) {
                        $str .= 'Сцепка ';
                    }
                    if (!empty($vehicle['lorry'])) {
                        $str .= 'Грузовик ';
                    }


                    ?>
                    <a href="<?php echo $this->url(
                        'resource',
                        array('action' => 'add', 'id' => $resource['uuid'], 'type' => 'list')
                    );?>"> <?php

                        $strLoad = '';
                        foreach ($resource['typeLoad'] as $typeLoad) {
                            $strLoad .= $typeLoad . ', ';
                        }
                        echo $str . ' / ' . $vehicle['capacity'] . ' / ' . ' / ' . $strLoad;
                        ?>
                    </a>

                <?php
                } else {
                    echo 'Нет прикрепленого ресура';
                }
                ?>
            </td>
            <td>
                <?php
                if (!empty($acceptedResource)) {
                    ?>
                    <a href="<?php echo $this->url(
                        'ticket',
                        array('action' => 'createBill', 'id' => $ticket['id'])
                    );?>">Печать</a>
                <?php
                }
                ?>

            </td>
            <td>
                <?php echo $ticket['statusGlobal']; ?>
            </td>
            <td>
                <?php echo $ticket['statusWork']; ?>
            </td>
            <td>
                <?php echo $owner['property'] . ' ' . $owner['name']; ?>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'excel',
                    array('action' => 'getExcel', 'id' => $ticket['uuid'])
                );?>">Печать</a>
                </br>
                <a href="<?php echo $this->url(
                    'excel',
                    array('action' => 'generateTemplate', 'id' => $ticket['uuid'])
                );?>">Загрузить свой шаблон</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'add', 'id' => $ticket['uuid'], 'type' => 'edit')
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'interaction',
                    array('action' => 'add', 'id' => $ticket['uuid'])
                );?>">Добавить предложение</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'add', 'id' => $ticket['uuid'], 'type' => 'copy')
                );?>">Дублировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'delete', 'id' => $ticket['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>