<?php
$tickets=$this->tick;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>
<a href="<?php echo $this->url('ticket',
    array('action'=>'add'));?>">Добавить заявку</a>
<a href="<?php echo $this->url('ticket',
    array('action'=>'index'));?>">Все заявки</a>

<table class="table">
    <tr>
        <th>
            Типы перевозок
        </th>
        <th>
            Дата отрпавления / Прибытия
        </th>
        <th>
            Стоимость
        </th>
        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Добавить аукцион
        </th>
    </tr>
    <?php foreach ($tickets as $ticket) { //$ticket=$ticket['tick']; ?>
        <tr>
            <td>
                <?php foreach ($types_r as $key => $value) {
                    echo $key.' '.$ticket[$value].' ';
                }
                ?>
            </td>
            <td>
                <?php echo $ticket['dateStart'].' / '.$ticket['dateEnd']; ?>
            </td>
            <td>
                <?php echo $ticket['money'].' '.$ticket['currency']; ?>
            </td>
            <td>
                <a href="<?php echo $this->url('ticket',
                    array('action'=>'list', 'id' => $ticket['uuid']));?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url('ticket',
                    array('action'=>'edit', 'id' => $ticket['uuid']));?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url('auction',
                    array('action'=>'add', 'id' => $ticket['uuid']));?>">Добавить аукцион</a>
            </td>
        </tr>
    <?php } ?>

</table>