<?php
$tickets = $this->res;

$types_r = array('Тентовый' => 'tent', 'Фургон' => 'furgon', 'Пикап' => 'pickup', 'Муковоз' => 'mukovoz');
?>
<a href="<?php echo $this->url(
    'ticket',
    array('action' => 'add')
);?>">Добавить ресурс</a>
<a href="<?php echo $this->url(
    'ticket',
    array('action' => 'index')
);?>">Все ресурсы</a>

<table class="table">
    <tr>
        <th>
            Номер публикации
        </th>
        <th>
            Даты и времени готовности ТС к загрузке
        </th>
        <th>
            Место загрузки/разгрузки
        </th>
        <th>
            Тариф
        </th>
        <th>
            Вид транспортного средства
        </th>
        <th>
            Вид загрузки
        </th>
        <th>
            Грузоподъемность
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Добавить аукцион
        </th>
        <th>
            Копировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($tickets as $ticket) {
        $ticketWay=$ticket['ways'];
        $cargo=$ticket['veh'];
        $ticket=$ticket['res'];

        ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'list', 'id' => $ticket['uuid'])
                );?>"><?php echo $ticket['uuid']; ?></a>
            </td>
            <td>
                <?php
                foreach($ticketWay as $way) {
                    echo $way['dateStart'] . ' / ' . $way['timeStart'].'</br>';
                }
                ?>
            </td>
            <td>
                <?php
                foreach($ticketWay as $way) {
                    echo $way['areaLoad'] . ' / ' . $way['areaUnload'].'</br>';
                }
                ?>

            </td>
            <td>
                <?php
                foreach($ticketWay as $way) {

                    echo $way['money'] . ' ' . $way['currency'].'</br>';
                }
                ?>

            </td>

            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'list', 'id' => $cargo['uuid'])
                );?>"><?php echo $cargo['carNumber'].' '.$cargo['mark'] . ' / ' . $cargo['model']; ?></a>
            </td>
            <td>
                <?php echo $ticket['kindOfLoad']; ?>
            </td>
            <td>
                <?php echo $cargo['capacity']; ?>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'edit', 'id' => $ticket['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'auction',
                    array('action' => 'add', 'id' => $ticket['uuid'])
                );?>">Добавить аукцион</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'copy', 'id' => $ticket['uuid'])
                );?>">Копировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'ticket',
                    array('action' => 'delete', 'id' => $ticket['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>