<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('submit')->setAttribute('class', 'btn btn-primary');
?>

<?php echo $this->form()->openTag($form) ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="LoginFormLabel">Sign In</h3>
</div>
<div class="modal-body">

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
        <?php endif ?>

    </dl>

    <?php if ($this->enableRegistration) : ?>
        Not registered? <a href="<?php echo $this->url(
            'zfcuser/register'
        ) . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>">Sign up!</a>
    <?php endif; ?>

</div>
<div class="modal-footer">
    <a href="#" class="btn btn-link" data-dismiss="modal" aria-hidden="true">Close</a>
    <?php echo $this->formButton($form->get('submit')) ?>
</div>
<?php echo $this->form()->closeTag() ?>
