<?php
$form = $this->form;
$formData = $this->formData;
$form->setAttribute('action', $this->url('cargo', array('action' => 'addCargo')))
    ->prepare();
$name = $form->get('name');
$note = $form->get('note');


echo $this->form()->openTag($form);




?>
    <table class="table spec_table cargo">
        <tr>
            <th style="width:50%; text-align: center;">
                Какие-то поля
            </th>
            <th style="width:50%; text-align: center;">
                Какие-то поля
            </th>
        </tr>
        <tr style="border-right: 1px dashed #dddddd;">
            <td style="width:50%;">
                <?php

                echo $this->formRow($name);
                ?>


            </td>
            <td style="width:50%;">

            </td>
        </tr>
        <tr>
            <td>

            </td>
            <td>
                <?php  echo $this->formRow($note);
                ?>
            </td>
        </tr>
    </table>

    <div class="submit_cl"><?php echo $this->formElement($form->get('submit')); ?> </div>
<?php  echo $this->form()->closeTag();
?>