<?php
$cargos = $this->res;


?>
<a href="<?php echo $this->url(
    'cargo',
    array('action' => 'add')
);?>">Добавить ТС</a>
<a href="<?php echo $this->url(
    'cargo',
    array('action' => 'my')
);?>">Мои ТС</a>

<table class="table">
    <tr>
        <th>
           Номер транспортного средства
        </th>
                <th>
                    Статус
                </th>
        <th>
            Марка / Модель
        </th>

        <th>
            Организация
        </th>
        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($cargos as $cargo) { $org=$cargo['org'];$cargo=$cargo['res'];?>
        <tr>
            <td>
                 <?php echo $cargo['carNumber']; ?>
            </td>
                        <td>
                            <?php echo $cargo['status']; ?>
                        </td>
            <td>
                <?php echo $cargo['mark'] . ' / ' . $cargo['model']; ?>
            </td>

                    <td>
                    <a href="<?php echo $this->url('organization',
                                array('action'=>'list', 'id' => $org['uuid']));?>"><?php echo $org['name']; ?></a>
                    </td>
            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'list', 'id' => $cargo['uuid'])
                );?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'edit', 'id' => $cargo['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'delete', 'id' => $cargo['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>