<?php
$cargos = $this->res;


?>
<h1>Все грузы</h1>
<a href="<?php echo $this->url(
    'cargo',
    array('action' => 'add')
);?>">Добавить ТС</a>
<a href="<?php echo $this->url(
    'cargo',
    array('action' => 'my')
);?>">Мои ТС</a>

<table class="table">
    <tr>
        <th>

        </th>
                <th>

                </th>
        <th>

        </th>

        <th>
            Организация
        </th>
        <th>
            Подробнее
        </th>
        <th>
            Редактировать
        </th>
        <th>
            Удалить
        </th>
    </tr>
    <?php foreach ($cargos as $cargo) { $org=$cargo['org'];$cargo=$cargo['res'];?>
        <tr>
            <td>

            </td>

            <td>

            </td>

                    <td>

            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'list', 'id' => $cargo['uuid'])
                );?>">Подробнее</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'edit', 'id' => $cargo['uuid'])
                );?>">Редактировать</a>
            </td>
            <td>
                <a href="<?php echo $this->url(
                    'cargo',
                    array('action' => 'delete', 'id' => $cargo['uuid'])
                );?>">Удалить</a>
            </td>
        </tr>
    <?php } ?>

</table>