<?php
$tickets=$this->res;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>

<h1>Грузы моего аккаунта</h1>

<table class="table">
    <tr>
        <th>
            Пункт загрузки
        </th>
        <th>
            Пункт выгрузки
        </th>
        <th>
            Грузовладелец
        </th>
        <th>
            Компания (создавшая груз)
        </th>
        <th>
            Тип ТС
        </th>

    </tr>
    <?php foreach ($tickets as $ticket) {
        $ticketWay=$ticket['ways'];
        $cargo=$ticket['veh'];
        // $acc=$ticket['org'];
        $owner=$ticket['owner'];
        $ticket=$ticket['res'];
        foreach($ticketWay as $way){
            ?>
            <tr>
                <td>
                    <?php echo $way['areaLoad']; ?>
                </td>
                <td>
                    <?php echo $way['areaUnload']; ?>
                </td>
                <td>
                    <?php echo $way['cargoOwnerTrue']['property'].' '.$way['cargoOwnerTrue']['name']; ?>
                </td>
                <td>
                    <?php echo $owner['property'].' '.$owner['name']; ?>
                </td>
                <td>
                    <?php echo $way['type']; ?>
                </td>

            </tr>
        <?php }} ?>

</table>