<?php
$tickets=$this->res;

$types_r=array('Тентовый'=>'tent', 'Фургон' => 'furgon', 'Пикап'=> 'pickup', 'Муковоз'=>'mukovoz');
?>

<h1>Мои грузы</h1>

<table class="table">
    <tr>
        <th>
            Пункт загрузки
        </th>
        <th>
            Пункт выгрузки
        </th>
        <th>
            Грузовладелец
        </th>
        <th>
            Тип ТС
        </th>

    </tr>
    <?php foreach ($tickets as $ticket) {
        $ticketWay=$ticket['ways'];
        $cargo=$ticket['veh'];
        $org=$ticket['org'];
        $ticket=$ticket['res'];
        foreach($ticketWay as $way){
            ?>
            <tr>
                <td>
                    <?php echo $way['areaLoad']; ?>
                </td>
                <td>
                    <?php echo $way['areaUnload']; ?>
                </td>
                <td>
                    <?php echo $way['cargoOwner']; ?>
                </td>
                <td>
                    <?php echo $way['type']; ?>
                </td>

            </tr>
        <?php }} ?>

</table>