<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cargo</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet" media="all">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="css/cargo.min.css" rel="stylesheet" media="all">
    <link href="css/cargo.handheld.min.css" rel="stylesheet" media="handheld">
    <link rel="shortcut icon" href="img/ico/favicon.ico">
    <link rel="icon" href="img/ico/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="img/ico/favicon.ico" type="image/x-icon">
    <link rel="icon" href="img/ico/coast-browser-icon-228x228.png" sizes="228x228">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="img/ico/apple-touch-icon-144x144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="img/ico/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/ico/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/ico/apple-touch-icon-57x57-precomposed.png">
    <meta name="application-name" content=" Cargo "/>
    <meta name="msapplication-TileColor" content=" #6DB700"/>
    <meta name="msapplication-square70x70logo" content="img/ico/ie11-pinned-70x70.png"/>
    <meta name="msapplication-square150x150logo" content="img/ico/ie11-pinned-150x150.png"/>
    <meta name="msapplication-wide310x150logo" content="img/ico/ie11-pinned-310x150.png"/>
    <meta name="msapplication-square310x310logo" content="img/ico/ie11-pinned-310x310.png"/>

    <!--[if lt IE 9]>
    <script src="//html5shiv.googmain_pagelecode.com/svn/trunk/html5.js"></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.1.0/es5-sham.min.js'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.1.0/es5-shim.min.js'></script>
    <![endif]-->

    <!--[if lte IE 8]>
    <script src="lib/json3/json3.min.js"></script>
    <![endif]-->
</head>
<body>
<div>
    <div>
        <div id="sign_in_block" class="filled_bg">
            <div class="container">

                <h1 class="marketing_header">Поздравляем с регистрацией в нашем сервисе!</h1>

                <p class="marketing_subheader">Грузоперевозки с удобством</p>
            </div>
        </div>
    </div>


    <div class="container">
        <div id="self_presentation_block">
            <p>Для начала работы с сервисом Ваш профиль должен быть активированы нашим специалистом.</p>
            <p>Через некоторое время Вам придет уведомление об активации. Пожалуйста, подождите немного.</p>
        </div>
    </div>

    <div class="filled_bg">
        <div class="container">
            <ul id="features_block">
                <li>
                    <h2>Feature 1</h2>

                    <p>Our killer feature</p>
                </li>
                <li>
                    <h2>Feature 2</h2>

                    <p>Our killer feature</p>
                </li>
                <li>
                    <h2>Feature 3</h2>

                    <p>Our killer feature</p>
                </li>
                <li>
                    <h2>Feature 4</h2>

                    <p>Our killer feature</p>
                </li>
                <li>
                    <h2>Feature 5</h2>

                    <p>Our killer feature</p>
                </li>
                <li>
                    <h2>Feature 6</h2>

                    <p>Our killer feature</p>
                </li>
            </ul>
        </div>
    </div>

    <div class="container">
        <table id="pricing" class="table">
            <th>Basic</th>
            <th>Professional</th>
            <th>Business</th>
            <th>Enterprise</th>
            <tr>
                <td>$5/MO</td>
                <td>$10/MO</td>
                <td>$15/MO</td>
                <td>$20/MO</td>
            </tr>
            <tr>
                <td>1 route</td>
                <td>2 routes</td>
                <td>5 routes</td>
                <td>100 routes</td>
            </tr>
            <tr>
                <td>none</td>
                <td>yes</td>
                <td>yes</td>
                <td>unlimited</td>
            </tr>
        </table>
    </div>
</div>
<br/>
</body>
</html>
