<?php

$displayName = $this->zfcUserIdentity() ? $this->zfcUserIdentity()->getDisplayname() : '';

echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Карго')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => '/image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
        )
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile(
        $this->basePath() . '/js/html5.js',
        'text/javascript',
        array('conditional' => 'lt IE 9',)
    )
        ->prependFile($this->basePath() . '/js/common.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->url('home') ?>">Грузоперевозки</a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>">Главная</a></li>
                </ul>
                <ul class="nav pull-right">
                    <?php if (!$this->zfcUserIdentity()): ?>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/register') ?>">
                                Регистрация
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/login') ?>"
                               class="js"
                               data-event="click"
                               data-handler="App.Login.dialog"
                               data-content="#login-form">
                                Войти&nbsp;<i class="icon-off icon-white"></i>
                            </a>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?php echo $this->url('zfcuser') ?>">
                                <i class="icon-user icon-white"></i>&nbsp;<?php echo $displayName; ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('zfcuser/logout') ?>">
                                Выйти&nbsp;<i class="icon-off icon-white"></i>
                            </a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div id="login-form"
     class="modal hide fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="LoginFormLabel"
     aria-hidden="true">
    <?php echo $this->zfcUserLoginWidget(); ?>
</div>
<div class="container">
    <div class="hero-unit">
        <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
        <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
        <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
    </div>

    <div class="row">

        <div class="span4">
            <h2><?php echo $this->translate('Follow Development') ?></h2>
            <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="http://framework.zend.com/issues/browse/ZF2">', '</a>') ?></p>
            <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
        </div>

        <div class="span4">
            <h2><?php echo $this->translate('Discover Modules') ?></h2>
            <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
            <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
        </div>

        <div class="span4">
            <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
            <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
            <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
        </div>
    </div>
</div>
<!-- /container -->
<footer class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <span class="brand" href="#">&copy;&nbsp;2013&nbsp;СП Онлайн</span>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>