<?php
return array(
    'navigation' => array(
        'top-menu' => array(
            array(
                'label' => 'Главная',
                'route' => 'dashboard',
                'group' => 'left',
                'resource'   => 'route/dashboard',
            ),
            array(
                'label' => 'Админка',
                'route' => 'zfcadmin',
                'group' => 'left',
                'resource'   => 'route/zfcadmin',
            ),
            array(
                'label' => 'Регистрация',
                'route' => 'zfcuser/register',
                'group' => 'right',
                'resource'   => 'route/zfcuser/register',
            ),
            array(
                'label' => '##USERNAME##',
                'route' => 'zfcuser',
                'group' => 'right',
                'resource'   => 'route/zfcuser',
                'pages' => array(
                    array(
                        'label' => 'Профиль',
                        'route' => 'zfcuser',
                        'group' => 'right',
                        'resource'   => 'route/zfcuser',
                    ),
                    array(
                        'label' => 'Аккаунты',
                        'route' => 'organization',
                        'group' => 'right',
                        'params' => array('id' => null),
                        'resource'   => 'route/organization',
                    ),
                    array(
                        'label' => '',
                        'type' => 'uri',
                        'uri' => '',
                        'class' => 'divider',
                        'resource'   => 'route/zfcuser/logout',
                    ),
                    array(
                        'label' => 'Выйти',
                        'route' => 'zfcuser/logout',
                        'resource'   => 'route/zfcuser/logout',
                    ),
                ),
            ),
            array(
                'label' => 'Войти',
                'route' => 'zfcuser/login',
                'group' => 'right',
                'class' => 'js',
                'data-event' => "click",
                'data-handler' => "App.Login.dialog",
                'data-content' => "#login-form",
                'icon' => 'icon-off',
                'resource'   => 'route/zfcuser/login',
            ),
        ),
        'sidebar' => array(
            array(
                'label' => 'Организация',
                'route' => 'organization',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/organization',
            ),
            array(
                'label' => 'Доска оповещений',
                'route' => 'notification',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/notification',
            ),
            array(
                'label' => 'Новые оповещения',
                'route' => 'notification',
                'action' => 'new',
                'params' => array('id' => null),
                'resource'   => 'route/notification',
            ),
            array(
                'label' => 'Рерусы',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/resource',
            ),
            array(
                'label' => 'Все',
                'route' => 'resource',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'controller/Resource\Controller\Resource:index',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'resource',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'controller/Resource\Controller\Resource:my',
            ),
            array(
                'label' => 'Поиск',
                'route' => 'resource',
                'action' => 'search',
                'params' => array('id' => null),
                'resource'   => 'controller/Resource\Controller\Resource:search',
            ),
            array(
                'label' => 'Транспорт',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/vehicle',
            ),
            array(
                'label' => 'Все',
                'route' => 'vehicle',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'controller/Resource\Controller\Vehicle:index',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'vehicle',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'controller/Resource\Controller\Vehicle:my',
            ),
            array(
                'label' => 'Заявки',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/ticket',
            ),
            array(
                'label' => 'Все',
                'route' => 'ticket',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'controller/Ticket\Controller\Ticket:index',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'ticket',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'controller/Ticket\Controller\Ticket:my',
            ),
            array(
                'label' => 'Поиск',
                'route' => 'ticket',
                'action' => 'search',
                'params' => array('id' => null),
                'resource'   => 'controller/Ticket\Controller\Ticket:search',
            ),
            array(
                'label' => 'Грузы',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/cargo',
            ),
            array(
                'label' => 'Все',
                'route' => 'cargo',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'controller/Ticket\Controller\Cargo:index',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'cargo',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'controller/Ticket\Controller\Cargo:my',
            ),
            array(
                'label' => 'Предложения',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Отправленные',
                'route' => 'interaction',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Полученные',
                'route' => 'interaction',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Аукцион',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/auction',
            ),
            array(
                'label' => 'Аукционы',
                'route' => 'auction',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/auction',
            ),
        ),
        'admin' => array(
            array(
                'label' => 'Управление юзерами',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/company_user',
            ),
            array(
                'label' => 'Все юзеры',
                'route' => 'company_user',
                'action' => 'list',
                'params' => array('org_id' => 'all'),

            ),
            array(
                'label' => 'Справочники',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Мои справочники',
                'route' => 'addList',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'ТС Марка',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '470c1d9273094cc4a8a60134ad2831bf'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'ТС Модель',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'f6aee9deef67464aadac4b692f7901ad'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'ТС Статус',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'd3a157f442524771aa86dbb125da934b'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'ТС Тип',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'ad1f2dcc5b7b4829b26a59234a85b97f'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Компания Формы собственности',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'e40c1bd0e19b43488b238a9ff4fbe10e'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Компания Реквизиты',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'f6fddce266b7470dba816efb27309455'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Заявка Имя груза',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '1a93295b9b0947d1942884e2f53c4b59'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Заявка Вид документа',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '2c8855580ea24721880cc586bc436a57'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Вид загрузки',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '14c84c5e3e254a06b91f7e9cd850e4a9'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Статус предложения',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'c83043049ac946aba1d358a1c4eb5a1b'),
                'resource'   => 'route/addList',
            ),
        ),
    ),
);
