<?php
return array(
    'navigation' => array(
        'top-menu' => array(
            array(
                'label' => 'Главная',
                'route' => 'dashboard',
                'group' => 'left',
                'resource'   => 'route/dashboard',
            ),
            array(
                'label' => 'Админка',
                'route' => 'zfcadmin',
                'group' => 'left',
                'resource'   => 'route/zfcadmin',
            ),
            array(
                'label' => 'Регистрация',
                'route' => 'zfcuser/register',
                'group' => 'right',
                'resource'   => 'route/zfcuser/register',
            ),
            array(
                'label' => '##USERNAME##',
                'route' => 'zfcuser',
                'group' => 'right',
                'resource'   => 'route/zfcuser',
                'pages' => array(
                    array(
                        'label' => 'Профиль',
                        'route' => 'zfcuser',
                        'group' => 'right',
                        'resource'   => 'route/zfcuser',
                    ),
                    array(
                        'label' => 'Аккаунты',
                        'route' => 'organization',
                        'group' => 'right',
                        'params' => array('id' => null),
                        'resource'   => 'route/organization',
                    ),
                    array(
                        'label' => '',
                        'type' => 'uri',
                        'uri' => '',
                        'class' => 'divider',
                        'resource'   => 'route/zfcuser/logout',
                    ),
                    array(
                        'label' => 'Выйти',
                        'route' => 'zfcuser/logout',
                        'resource'   => 'route/zfcuser/logout',
                    ),
                ),
            ),
            array(
                'label' => 'Войти',
                'route' => 'zfcuser/login',
                'group' => 'right',
                'class' => 'js',
                'data-event' => "click",
                'data-handler' => "App.Login.dialog",
                'data-content' => "#login-form",
                'icon' => 'icon-off',
                'resource'   => 'route/zfcuser/login',
            ),
        ),
        'sidebar' => array(
            array(
                'label' => 'Организация',
                'route' => 'organization',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/organization',
            ),
            array(
                'label' => 'Доска оповещений',
                'route' => 'notification',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/notification',
            ),
            array(
                'label' => 'Новые оповещения',
                'route' => 'notification',
                'action' => 'new',
                'params' => array('id' => null),
                'resource'   => 'route/notification',
            ),
            array(
                'label' => 'Рерусы',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/resource',
            ),
            array(
                'label' => 'Все',
                'route' => 'resource',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/resource',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'resource',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/resource',
            ),
            array(
                'label' => 'Поиск',
                'route' => 'resource',
                'action' => 'search',
                'params' => array('id' => null),
                'resource'   => 'route/resource',
            ),
            array(
                'label' => 'Транспорт',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/vehicle',
            ),
            array(
                'label' => 'Все',
                'route' => 'vehicle',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/vehicle',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'vehicle',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/vehicle',
            ),
            array(
                'label' => 'Заявки',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/ticket',
            ),
            array(
                'label' => 'Все',
                'route' => 'ticket',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/ticket',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'ticket',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/ticket',
            ),
            array(
                'label' => 'Поиск',
                'route' => 'ticket',
                'action' => 'search',
                'params' => array('id' => null),
                'resource'   => 'route/ticket',
            ),
            array(
                'label' => 'Грузы',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/cargo',
            ),
            array(
                'label' => 'Все',
                'route' => 'cargo',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/cargo',
            ),
            array(
                'label' => 'Собственные',
                'route' => 'cargo',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/cargo',
            ),
            array(
                'label' => 'Предложения',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Отправленные',
                'route' => 'interaction',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Полученные',
                'route' => 'interaction',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/interaction',
            ),
            array(
                'label' => 'Аукцион',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/auction',
            ),
            array(
                'label' => 'Аукционы',
                'route' => 'auction',
                'action' => 'index',
                'params' => array('id' => null),
                'resource'   => 'route/auction',
            ),
        ),
        'admin' => array(

            array(
                'label' => 'Справочники',
                'type' => 'uri',
                'uri' => '',
                'class' => 'nav-header',
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Мои справочники',
                'route' => 'addList',
                'action' => 'my',
                'params' => array('id' => null),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Марка ТС',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '2258f8bc165842a48c6dd2c6f0a2157b'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Модель ТС',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'b3c8ad8bd32e4d8fb439a4c09b7edd75'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Статусы ТС',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '21a05595304a451da912652a816de645'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Тип ТС',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'f7f0fbb3be874011969ae0e4322d5a37'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Формы собственности компаний',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '56034bc8b49d4f05a094c142363a94ab'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Реквизиты компаний',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '1c25bf22c7514891a2ed6ab19452c4f6'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Заявка - груз',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'a04f1b475c6648f195d4f0978dccd1fa'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'тип загрузки',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '83917605d9bc450e9c1da9ee03ef0cc0'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'тип выгрузки',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '6c455e756a0943afb90b22187dfc5c07'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'тип ТС',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => '105863b25e1046c68fa69289f182da7e'),
                'resource'   => 'route/addList',
            ),
            array(
                'label' => 'Статус предложения',
                'route' => 'addList',
                'action' => 'my-fields',
                'params' => array('id' => 'c83043049ac946aba1d358a1c4eb5a1b'),
                'resource'   => 'route/addList',
            ),
        ),
    ),
);
