<?php
$param=$this->param;
$form = $this->form;
$form->setAttribute('action', $this->url('company_user', array('action' => 'addUser', 'org_id' => $this->org_id, 'param' =>$param)))
    ->prepare();

echo $this->form()->openTag($form);

$org = $form->get('company_user');
echo $this->formRow($org->get('email'));
echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
