<?php
$users=$this->users;
$param=null;
$comId=null;

if($this->org_uuid=='all') {
    $param='full';
} else {
    $comId=$this->org_uuid;
}

?>
<h1>Список юзеров</h1>



<table class="table">
    <tr>
        <th>Email</th>
        <th>Имя юзера</th>
        <?php if($param!='full') { ?>
        <th>Изменить роль юзера</th>
        <?php } ?>
        <?php if( (!empty($users[0]['orgName'])) && (!empty($users[0]['comName'])) ) { ?>
        <th>Аккаунт / Компания</th>
        <?php }?>
        <th>Удалить юзера</th>
    </tr>
<?php
foreach($users as $user) {
    ?>
    <tr>
        <td><?php echo $user['email']; ?></td>
        <td><?php echo $user['username']; ?></td>
        <?php if($param!='full') { ?>
        <td><a href="<?php
                echo $this->url('company_user', array('action'=>'role', 'org_id' =>$user['id'], 'param' => 'company', 'comId'=>$comId));

            ?>

            ">Роль</a>
        </td>
        <?php } ?>
        <?php if( (!empty($users[0]['orgName'])) && (!empty($users[0]['comName'])) ) { ?>
        <td><?php echo $user['orgName'].' / '.$user['comName']; ?></td>
        <?php }?>
        <td><a href="<?php echo $this->url('company_user',
                array('action'=>'delete', 'org_id' => $user['id'], 'param' =>$param));?>">Удалить</a></td>
    </tr>
<?php
}
?>
</table>
