<?php
$users=$this->users;
$param=null;


if($this->org_uuid=='all') {
    $param='full';

}

?>
<h1>Список юзеров</h1>



<table class="table">
    <tr>
        <th>Email</th>
        <th>Имя юзера</th>
        <th>Изменить роль юзера</th>
        <th>Удалить юзера</th>
    </tr>
<?php
foreach($users as $user) {
    ?>
    <tr>
        <td><?php echo $user['email']; ?></td>
        <td><?php echo $user['username']; ?></td>
        <td><a href="<?php
            if(empty($param)) {
                echo $this->url('company_user', array('action'=>'role', 'org_id' =>$user['id']));
            } elseif($param=='full') {
                echo $this->url('company_user', array('action'=>'role', 'org_id' =>$user['id'], 'param' => 'admin'));
            }

            ?>

            ">Роль</a></td>
        <td><a href="<?php echo $this->url('company_user',
                array('action'=>'delete', 'org_id' => $user['id'], 'param' =>$param));?>">Удалить</a></td>
    </tr>
<?php
}
?>
</table>
